### ISSUE TITLE
Resolve incorrect language detection for ios/Safari

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#1005]
Right now, users of Safari/iOS will not see translations, due to the wrong `accept-language` header being sent - it's lowercased (`en_us`) instead of properly cased (`en_US`) which results in no match on the language file to be sent.  For our copy I've just added a rewrite to nginx, but this is less than ideal.  Here's that:

```
rewrite ^/locales/en_us.json /locales/en_US.json last;
```

This [was fixed in Angular Translate already](https://github.com/angular-translate/angular-translate/issues/431) so I'm not sure why we're still having the problem.  Maybe we haven't updated?

via @cmbirk

**Comment by doshitan** [comment]
I think we need to add a `$translateProvider.uniformLanguageTag('java')` to our `client/app/js/modules/translate.js` file as [noted in the docs](http://angular-translate.github.io/docs-canary/#/api/pascalprecht.translate.%24translateProvider#methods_uniformlanguagetag).

**Comment by krues8dr** [comment]
Nice reading of the docs there @doshitan :)  Something I failed to do effectively!
