### ISSUE TITLE
Issue switching between accounts — "Use Madison As" 

### ISSUE THREAD

**Issue by deniselinn** [opengovfoundation/madison#1024]
I can't switch back and forth between accounts under "Use Madison As." Once I switch to using Madison as my organization, the menu changes and displays my organization twice, preventing me from switching back to using Madison personally.

Another component of this problem: after switching to an organization account, annotation and comments are still listed under my own name. There is not way to know which name it will be listed under until the comment is submitted (and can't be deleted). 

![use madison as inaccurate - no person account listed](https://cloud.githubusercontent.com/assets/13007513/16533382/f07a5886-3f9d-11e6-9f35-ab8acb5802ad.png)
![use madison as accurate - both accounts](https://cloud.githubusercontent.com/assets/13007513/16533383/f07afa8e-3f9d-11e6-9985-6449ecf7f847.png)

**Comment by krues8dr** [comment]
Thanks for the report.  We encountered this over in #922 as well and are looking at a better way to handle this.

**Comment by sethetter** [comment]
No longer a feature in v4.
