### ISSUE TITLE
Issue with comment csv export

### ISSUE THREAD

**Issue by deniselinn** [opengovfoundation/madison#1027]
The csv of comments/annotations that admins can download for a document does not get updated right away. For example, there are 34 comments and 46 annotations in the Array of Things Governance & Privacy Policy, but as of the morning of 7/6 the comments csv file (and the statistics tab) do not register any new additions that were made on 7/5.

**Comment by krues8dr** [comment]
Ah.  The comments file currently doesn't export comments added by the sponsor's staff (per DC's request).  We can change this to be an option.

**Comment by sethetter** [comment]
Fixed in 55ca160!

Should be good to go now @deniselinn.

**Comment by krues8dr** [comment]
Note that the labels for these download buttons won't look right until you've cleared your browser cache.  (This is another bug fixed by Madison 3.0.)
