### ISSUE TITLE
Can't get/copy a link to individual "Discussion" comments

### ISSUE THREAD

**Issue by deniselinn** [opengovfoundation/madison#1031]
The blue link at the bottom right corner of a comment in "Discussion" doesn't seem to copy a link the same way a link is generated/copied for annotations within the document itself.

**Comment by krues8dr** [comment]
The permalink here is using Flash (via ZeroClipboard) to copy to the clipboard, and not generating a standard link - since Flash is effectively dead, we should replace this with a normal permalink and let the user copy it themselves if they want to.
