### ISSUE TITLE
Create UUIDs for permalinks for notes/annotations/comments/etc

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#1035]
We should ideally use a UUID scheme for permalinks moving forward, instead of the weird thing we're doing now.  Ideally, this will be nice, friendly short UUIDs like bit.ly and twitter use, rather than huge ugly real UUIDs.  Something like [this](https://github.com/ivanakimov/hashids.php) or something else which prevents offensive words, uses mixed case, etc.  There's probably a laravel module for this I haven't found yet.  Obviously, this will increase the complexity of our lookups on the document page for these, since we need to know what part of the page to reveal.

**Comment by doshitan** [comment]
This is resolved in v4.
