### ISSUE TITLE
Group validation needs some love

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/madison#1047]
Currently validation happens in a single `validate()` method on the Group model. We are moving to a pattern of using Form Request objects for validation and authorization.

Furthermore, group related routes do not utilize model binding, but they should.

Furthermore, we should remove any extra single attribute update routes and consolidate into the single `update` route and contain conditional logic in the Form Request object for authorization and validation rules.

Lastly, the client will need updated to only use this new and improved update route.

**Comment by doshitan** [comment]
This is resolved in v4.
