### ISSUE TITLE
What to use for latest stable?

### ISSUE THREAD

**Issue by kyrylkov** [opengovfoundation/madison#1058]
Is it `master` branch or `madison-3`?  Didn't find it covered anywhere.

Proper GitHub releases / tagging would also help as I almost downloaded 1.8.5 as the latest before reading elsewhere it's already 3.x

**Comment by sethetter** [comment]
@kyrylkov master is current stable. Thanks for pointing out the hanging branch ;)

**Comment by kyrylkov** [comment]
@sethetter so I can safely pull changes from `master` on the regular basis?

**Comment by sethetter** [comment]
@kyrylkov yes, the intention is to keep `master` always stable
