### ISSUE TITLE
apache vhost configuration triggers an error

### ISSUE THREAD

**Issue by IuliiSe** [opengovfoundation/madison#1062]
Apache does not restart after setting up the apache vhost by following the example configuration as seen in docs/apache.conf.example
`
apache2[29815]: AH00526: Syntax error on line 15 of /etc/apache2/sites-enabled/apache.conf:
apache2[29815]: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
apache2[29815]: Action 'configtest' failed.`

**Comment by sethetter** [comment]
@IuliiSe could you show the contents of that file? Could you also show the operating system and apache version being used?

**Comment by IuliiSe** [comment]
Apache/2.4.18 (Ubuntu)

Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-42-generic x86_64)

**Comment by IuliiSe** [comment]
Solved

**Comment by sethetter** [comment]
@IuliiSe great! What was the issue?

**Comment by IuliiSe** [comment]
Needed to activate mod_rewrite

`sudo a2enmod rewrite`

**Comment by sethetter** [comment]
That would do it ;) glad it's resolved!
