### ISSUE TITLE
email notifications - sendgrid 

### ISSUE THREAD

**Issue by IuliiSe** [opengovfoundation/madison#1067]
I have an issue with the mail service.

The app does not send out email notifications.

I've configured Sendgrid credentials in `.env` and tested it via telenet (`telnet smtp.sendgrid.net 587`.

It works. I can send out emails manually.

**What should I look into?** Can it be the issue with cache? Or database permissions? Or permissions on `client/app/js/routes.js`?

.env looks like that:
```
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database

MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=info@sunrise4am.eu
MAIL_PASSWORD=*******
MAIL_ENCRYPTION=tsl
MAIL_FROM_ADDRESS=notifications@sunrise4am.eu
MAIL_FROM_NAME=Sunrise4am

USERVOICE=null

COOKIE_DOMAIN=.sunrise4am.eu
```

**Comment by sethetter** [comment]
@IuliiSe you can check a few things

* The database table for `jobs`. If this has some sitting in it then there are jobs being created but failing to be processed. If it's empty, either they are getting created and processed successfully or are failing to be created.
* The laravel log file at `server/storage/logs/laravel.log`. See if there is anything about jobs or queuing.
* Check the status of the `laravel-worker` service, make sure it's running properly.
* Your sendgrid dashboard to see if the emails are being received by their API and processed.

**Comment by IuliiSe** [comment]
The jobs were created, but not processed. There were many queued issues in jobs table which look like that:
```
 | 105 | default | {"job":"mailer@handleQueuedMessage","data":{"view":"email.signup","data":{"token":"iSVT5uNVGuaJJLEf"},"callback":"C:32:\"SuperClosure\\SerializableClosure\":2678:{a:5:{s:4:\"code\";s:216:\"function ($message) use($user) {\n    $message->subject('Welcome to the Madison Community');\n    $message->from('sayhello@opengovfoundation.org', 'Madison');\n    $message->to($user->email);
```
Apparently, `RemindersController.php` did not get the new email settings and used the deafaults.

**Comment by sethetter** [comment]
No you shouldn't need to change anything there. That's Laravel source code, so that should always stay untouched.

Is your `.env` file under `{app_dir}/shared/server/`?

Did you check that the `laravel-worker` service?

**Comment by IuliiSe** [comment]
There is no `laravel-worker.conf` on my side :(
