### ISSUE TITLE
Anchoring of sidebar annotations on tables breaking

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#1072]
https://documents.mymadison.io/docs/america-first-a-budget-blueprint-to-make-america-great-again#heading-26

I'm rather sure this is something to do with how I set it up to get the parent elements to anchor to – I never expected tables to be used.

**Comment by krues8dr** [comment]
I *think* this is the offending code: https://github.com/opengovfoundation/madison/blob/master/client/app/js/services/annotationService.js#L19-L52

**Comment by sethetter** [comment]
@krues8dr BILL! :grinning: 

Thanks for that. Should have it fixed now!

**Comment by krues8dr** [comment]
Nice work! 👍
