### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by kintovt** [opengovfoundation/madison#1075]
hi, i'm never use laravel and php before, but i like madison project and i'm trying to localize it to russian.

on installation stage, when i try to execute "make db-reset", it fails with foreign constraint error on migration and data seed steps.
i made migration manually and disabled constraints check in seeds scripts and successfully finished installation and deployment of madison.
all works fine, but when i tryed to add user or comment document, madison fails with foreign constraint error. i disabled constraints check on every script  that throw that exception and all works fine, but i don't know is it safe and acceptable. 
can you help me with that?

**Comment by sethetter** [comment]
@kintovt are you using the Vagrant setup? If not that's definitely what I would recommend!
Otherwise, what is your database (mysql / mariadb?) and version?

**Comment by kintovt** [comment]
@sethetter thanks for answer.
i tried vagrant setup and all works fine. you may be right that problem is in mariadb version, because vagrant box have version 10 and my server had version 5 from centos base repository.

**Comment by sethetter** [comment]
@kintovt great! Happy to hear that worked :) let us know if you have any other troubles.
