### ISSUE TITLE
Password reset redirects to 404

### ISSUE THREAD

**Issue by mshenfield** [opengovfoundation/madison#1085]
Resetting the password at `/password/reset` redirects to `/home`, a non-existent page.

![screen shot 2018-02-25 at 12 03 26 pm](https://user-images.githubusercontent.com/4812055/36644700-e8ffed5c-1a23-11e8-9481-a3f8a14fad50.png)

**Comment by sethetter** [comment]
@mshenfield thanks for reporting this! We'll get it resolved.
