### ISSUE TITLE
Top related stories on right side of page

### ISSUE THREAD

**Issue by michaelhardesty** [opengovfoundation/madison#109]
on ValleyWag/Gawker, there’s a list of titles under “Top Stories” on the left side of the page, http://valleywag.gawker.com/

Once you click on an article (http://valleywag.gawker.com/twitter-fires-hated-exec-1506117610), that section turns to a “Recommended by ____” … this section can be a space for bills related to that certain bill or other bills in that same subsection

**Comment by cmbirk** [comment]
Closing this in favor of the new designs.
