### ISSUE TITLE
Playing video / audio from hearings on related document pages

### ISSUE THREAD

**Issue by bryanconnor** [opengovfoundation/madison#310]
Based on my chat with @cmbirk I wanted to put up a few options for this. 

The first one that came to mind puts the live event pretty front and center. 
![screen shot 2014-06-25 at 4 53 08 pm](https://cloud.githubusercontent.com/assets/1190829/3391493/c91013e0-fcaa-11e3-8682-eea2df83f377.png)

Here's an audio only for that same view.
![screen shot 2014-06-25 at 4 54 48 pm](https://cloud.githubusercontent.com/assets/1190829/3391529/045c8532-fcab-11e3-8af3-3a2ef3b6124f.png)

The only other idea I had was to include it pretty small in the sidebar.
![screen shot 2014-06-25 at 4 55 28 pm](https://cloud.githubusercontent.com/assets/1190829/3391544/263d70d0-fcab-11e3-8d90-2e8e8639a023.png)

If possible it would be great to have a recording of the video stored in a "Hearings" tab on this page for future reference.

**Comment by cmbirk** [comment]
Closing this in favor of the new designs.
