### ISSUE TITLE
Group dropdown gets cut off

### ISSUE THREAD

**Issue by rtsio** [opengovfoundation/madison#316]
The 'Change Group' menu goes offscreen. Using Chrome on Mac OS, 1440 x 900 res, window is 2/3 of desktop size.

![cutoff](https://cloud.githubusercontent.com/assets/3372355/3445645/6c1c46f2-0139-11e4-9d51-85fe6e86c56f.png)

**Comment by cmbirk** [comment]
This is solved.  We're simply displaying it on the left side now...
