### ISSUE TITLE
Testing suite

### ISSUE THREAD

**Issue by rtsio** [opengovfoundation/madison#337]
Instead of creating 40 separate issues, I'm going to track all the tests I've come up with here in Markdown @cmbirk @krues8dr .

+ Sign in
  - Attempting to sign in without email verification
  - [**functional**] Clicking on email link verifies account 
+ Request verified account
  - Verify with admin
  - [**functional**] Check that non-admin users are not authorized to verify
+ Request independent document sponsor
  - Verify with admin
  - [**functional**] Check that non-admin users are not authorized to verify
+ Create group
  - Verify with admin
  - [**functional**] Check that non-admin users are not authorized to verify
  - Add/delete group members
  - Change member roles
+ User changing active groups
+ Create document
  - Edit a document
  - Edit document metadata (status, sponsor, etc.)
+ Homepage filter/sort
+ Create annotation
+ Create annotation comment
+ Create comment
+ Document actions
  - Like/dislike
  - Support/oppose
  - Mark as seen
+ Static pages

**Comment by sethetter** [comment]
Closing in favor of #389
