### ISSUE TITLE
Elasticsearch BroadcastShardOperationFailedException

### ISSUE THREAD

**Issue by rtsio** [opengovfoundation/madison#361]
I am getting this on a clean database, clean pull, clean index and clean elasticsearch when trying to view documents on the homepage:

"{"count":0,"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"index":"madison","shard":1,"reason":"BroadcastShardOperationFailedException[[madison][1] ]; nested: QueryParsingException[[madison] request does not support [term]]; "},{"index":"madison","shard":2,"reason":"BroadcastShardOperationFailedException[[madison][2] ]; nested: QueryParsingException[[madison] request does not support [term]]; "},{"index":"madison","shard":3,"reason":"BroadcastShardOperationFailedException[[madison][3] ]; nested: QueryParsingException[[madison] request does not support [term]]; "},{"index":"madison","shard":4,"reason":"BroadcastShardOperationFailedException[[madison][4] ]; nested: QueryParsingException[[madison] request does not support [term]]; "},{"index":"madison","shard":0,"reason":"BroadcastShardOperationFailedException[[madison][0] ]; nested: QueryParsingException[[madison] request does not support [term]]; "}]}}"
type: "Elasticsearch\Common\Exceptions\BadRequest400Exception"

**Comment by cmbirk** [comment]
No longer using ES.
