### ISSUE TITLE
Notification email madison link should use base url

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#364]
In notifications.blade.php we have 

`<p> &nbsp;&ndash; Your friends at <a href="{{ url('/', $parameters = array(), $secure = null) }}">Madison</a>.</p>`

The linked text should be the full domain (ie. mymadison.io or dc.mymadison.io ) or provide that information somewhere else in the message.  This will help with confusion for users who are members of multiple instances.

**Comment by sethetter** [comment]
Notifications should all be good in v4 now!
