### ISSUE TITLE
Automate testing suite

### ISSUE THREAD

**Issue by rtsio** [opengovfoundation/madison#389]
@cmbirk here is what I've figured out so far:

Testing with chrome requires Chrome installed and the Selenium JAR to be running and configured with chromedriver path.

Testing with PhantomJS is easier. Run `npm install phantomjs` and then `phantomjs --webdriver=4444` (this can be automated using grunt). Change acceptance.suite.yml to use `browser: phantomjs`. Running a test like this, however, gives a very small window that cannot be resized without going into the Codeception/PHPUnit code that deals with controlling the WebDriver.

**Comment by sethetter** [comment]
I’m playing with ideas on how to set the `baseUrl` for protractor dynamically for travis / local.

The `COOKIE_SESSION` var in `.env` is the right thing to check for locally, but in Travis it looks like it will end up being something like `localhost:9000`. We can set it in an ENV var in the `travis.yml`, but pulling that into grunt locally would require using the node `dotenv` project, then checking for which one of the two env vars is available. Not sure if we want to do that or not? I could also just pull in the file and parse out the value for `COOKIE_SESSION`.

Thoughts, @cmbirk, @krues8dr?

**Comment by cmbirk** [comment]
I think we'll want to set it as an ENV variable in `.travis.yml`.  Which two variables are you referring to?

**Comment by sethetter** [comment]
I was thinking we would need to give the ENV var for `baseUrl` a different name in travis, but I don't think that will be necessary.

For pulling in the value of `COOKIE_SESSION` locally we'll need the node dotenv tool. Any opposition to pulling that in? Since there won't be a `.env` file in travis (right?) it will just end up having no effect in the CI server, and the ENV vars should already be set.

**Comment by cmbirk** [comment]
That works for me

**Comment by sethetter** [comment]
Just dropping a note in here that I plan to get this back to working after the work in #943.

**Comment by sethetter** [comment]
Since we have tests working in the 3.0 branches, I'm going to close this. We still need more test coverage, but the automation of testing is completed now.
