### ISSUE TITLE
Composer update runs out of memory

### ISSUE THREAD

**Issue by rtsio** [opengovfoundation/madison#413]
On running `composer update`, PHP will use over 1GB in memory and eventually stop. This depends on the environment, but I can't find what triggers it:

```PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar:///usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar/src/Composer/DependencyResolver/Solver.php on line 170```

This is a known issue with composer and may not be specific to Madison. The quick solution seems to be increasing the PHP memory limit so that composer can finish the update, though this may not be an option on low memory systems. See:

https://github.com/composer/composer/issues/1898
https://github.com/composer/composer/issues/2704
http://stackoverflow.com/questions/21815635/composer-running-out-of-memory-on-every-project-mac-os-x

**Comment by comefectiva** [comment]
:D!

**Comment by krues8dr** [comment]
The general advice for `composer` is to not run `composer update` if you're running out of memory - instead remove the installed libraries and run `composer install`.

I think this issue should be closed, as it's an upstream problem, and a note added to the README.

**Comment by cmbirk** [comment]
+1
