### ISSUE TITLE
Make ability to add members to a group more visible and usable

### ISSUE THREAD

**Issue by bryanconnor** [opengovfoundation/madison#424]
Currently the only way to add members to a group is to create the group then edit it again and see that a new text link has been added to add members. 

A quick fix would be to add a dedicated link to add members to the group listing page. When you create a group you are taken back to the list page where you see a link to add members. 

There should also be another button here to edit the settings of the group you have just created (as opposed to relying on a text link of the group's name only). This will help people understand how to use groups much faster.

**Comment by sethetter** [comment]
UX overhaul in v4, closing since this should be much better now.
