### ISSUE TITLE
Improvements to how the document table of contents looks and works

### ISSUE THREAD

**Issue by bryanconnor** [opengovfoundation/madison#433]
This design addresses the issue of the table of contents taking up a full column of space on a document page. It also questions whether it needs to always be visible. 

![toc](https://cloud.githubusercontent.com/assets/1190829/3818847/be00871e-1ce4-11e4-89e3-aaccf1e93340.gif)

It came up as a part of my redesign of the document page recently. I think hiding the table of contents by default and showing it on hover is a good way to focus the reader on the document itself and give it more space to breath. 

I think it would still be fixed as you scroll both in the open and closed state. 

It could also potentially indicate progress through the document in the closed state (through the dots) and in the open state through the color of the links.

**Comment by cmbirk** [comment]
Closing this in favor of our overall redesign.
