### ISSUE TITLE
Replace vagrant / puppet with Homestead

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#445]
[Homestead](http://laravel.com/docs/homestead) will be much easier to manage than our current vagrant / puppet setup.

**Comment by sethetter** [comment]
Given the work with #1013 (chef / capistrano) we should be able to easily configure a Vagrantfile to use the now available cookbooks.

**Comment by krues8dr** [comment]
Right, due to how we've got things setup now, Homestead isn't relevant anymore.
