### ISSUE TITLE
Change to the design of the document header

### ISSUE THREAD

**Issue by bryanconnor** [opengovfoundation/madison#447]
I wanted to discuss a change I'd like to make to the header of the document page. All the markup stays the same but the alignment and background of the doc-info area change. 

![doc-info-redesign](https://cloud.githubusercontent.com/assets/1190829/3913547/9a7fc8be-2337-11e4-9dae-44393cc4ec6d.png)

I think this is a big improvement to the document page but what do you guys think?
@cmbirk @leilis @seamuskraft @krues8dr @rtsio

**Comment by cmbirk** [comment]
Closing this in favor of our overall redesign.
