### ISSUE TITLE
Known issues with tests

### ISSUE THREAD

**Issue by rtsio** [opengovfoundation/madison#458]
Use this issue to track failing tests that we are aware of and know how to fix.

603455acb1e092c98666c46f86020008f352aaa6 passes if run from a local machine with Sauce Connect. Some issues are:

* Requesting verified status in Chrome will fail. The error will say that the `.alert-info` message was not found, because Chrome will actually be displaying an `.alert-danger` message due to not entering a phone number in the request. Protractor cannot sendKeys() to a `tel` field, I've opened an issue for this: https://github.com/angular/protractor/issues/1232
* Manual `browser.sleep()` calls must be put before each `expect()`. This is due to Protractor not waiting for the page to load if it is not part of Angular. I've found that a value of 4000 guarantees the page will load - lower values tend to fail intermittently.
* Tests do not work on Travis at all - I'm investigating this next. All sorts of strange issues here, "browser did not see any command for 90 secs" from Sauce, as well as fails on simple login tests.

**Comment by krues8dr** [comment]
Superceded by the new testing suite.
