### ISSUE TITLE
User Error--creating new account

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#469]
From user Anasha, email address me@anasha.us, browser Chrome 38.0.2125.101 (OS X 10.9):

"I tried to create an account. I may have clicked create twice, because I got an error saying that the account already existed. Then I tried to login and it said "Please click the link sent to your email to verify your account."

"I then clicked "resend confirmation email" because I never got one, and filled out that form, which resulted in an error message. "Whoops, looks like something went wrong." 
I still haven't seen a confirmation message, despite trying this a few times."

**Comment by cmbirk** [comment]
This should be resolved.
