### ISSUE TITLE
Page Jumping Around

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#472]
After I make a comment on the US Public Participation Guide, it kicks me back to the top of the page...so I have to scroll down and find where I left off each time.  Rather annoying.

**Comment by cmbirk** [comment]
This seems to only be happening with sub-comments.  I'm not sure why, but I'm going to bump to future for now so we can get this release out the door.

**Comment by sethetter** [comment]
New UI in v4!
