### ISSUE TITLE
Password Reset Not Working

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#482]
From user SBuckley, 12/5/2014 at 3:09pm
Browser: Chrome 39.0.2171.65 (Windows 7)

I forgot my password, so I have tried a number of times, over several days, to get it to reset. But I get nothing in my inbox.

I have checked my spam-box, but nothing there either.

Do you have any ideas about what to do?

P.S. I set up another account using my Gmail, but I don't want to experiment with a reset, since in case a glitch gets that one, too.

**Comment by cmbirk** [comment]
This is fixed with the referenced pull request.
