### ISSUE TITLE
Remove slashes when generating slug for docs

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#483]
Example:

US Public Participation Playbook Draft 2 -- 12/8/14

generated 

us-public-participation-playbook-draft-2----12/8/14

which caused errors trying to load the public view for obvious reasons.  When I edited the slug, it removed the slashes but it should remove them when generating initially as well.

Thanks @leilis for the heads up.

**Comment by krues8dr** [comment]
Closed in favor of #621
