### ISSUE TITLE
Vagrant setup needs some config tweaks to run without errors

### ISSUE THREAD

**Issue by rodowi** [opengovfoundation/madison#486]
This is how I fixed my local vagrant setup:

1) Composer was failing due to Github's API rate limits (see https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens)

% vagrant ssh
% vagrant@precise64:/vagrant$ composer config -g github-oauth.github.com your_oauth_token
% vagrant@precise64:/vagrant$ composer install

2) DB access failed
% cp app/config/example_creds.yml app/config/creds.yml

Edit creds.yml with puppet credentials

3) Re-provision

% vagrant provision

---

I would suggest adding the mentioned tweaks to the vagrant/puppet provisioning flow to overcome this issues.

**Comment by cmbirk** [comment]
Thanks @rodowi.  We're actually going to migrate to Laravel's [Homestead](http://laravel.com/docs/4.2/homestead), but I can certainly plug these in in the meantime.
