### ISSUE TITLE
 Error in exception handler.

### ISSUE THREAD

**Issue by philipjohn** [opengovfoundation/madison#493]
Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9.1
libyaml 0.1.4
mcrypt 2.5.8
MySQL 5.5.40
Laravel 4.1.25
node 0.10.25
Composer 1.0-dev
NPM 1.3.10

I'm pretty sure I have installed all the dependencies, and I've successfully run `composer install` but visiting Madison in the browser (having pointed Apache to the /public dir) I only see the following message:

> Error in exception handler.

My attempts to find out where that's coming from haven't been successful. There's nothing in the Apache or PHP error logs.

I also tried running grunt but received the following:

> $ grunt
> /usr/bin/env: node: No such file or directory

Any ideas where I might be going wrong? Thanks

**Comment by krues8dr** [comment]
Sounds like node isn't in your `PATH`?  This might help:  https://github.com/joyent/node/issues/3911

**Comment by krues8dr** [comment]
As to the first error, try setting `debug` to `true` in `config/app.php` to see if you get any more useful debug info.

**Comment by philipjohn** [comment]
Turned out to be as simple as file ownership. Thanks for the pointers!
