### ISSUE TITLE
Error message when saving documents on Madison 

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#496]
![screen shot 2015-02-05 at 7 04 12 pm](https://cloud.githubusercontent.com/assets/6437336/6071976/e9467260-ad69-11e4-9205-21f6ed4fdc3a.png)

(Resulted from clicking the "save" button at the bottom of a document I was editing)

**Comment by cmbirk** [comment]
Thanks @leilis .  We already have a fix in place in the issue477 branch that I'm working on.

**Comment by zaenulhilmi** [comment]
hi @cmbirk,  I still got the same error. "Document saved, but there was an error with Elasticsearch: Failed to connect to localhost port 9200: Connection refused". When you gonna merge that branch that has been fixed?

**Comment by cmbirk** [comment]
@zaenulhilmi we should have that branch merged by the end of the month.

**Comment by krues8dr** [comment]
Elasticsearch is removed, so this is effectively solved afaik.
