### ISSUE TITLE
Error messages in login popup are not being displayed

### ISSUE THREAD

**Issue by rodowi** [opengovfoundation/madison#500]
The JavaScript code that builds the html to show login errors in the login popup is broken.

![screen shot 2015-03-02 at 10 09 58 pm](https://cloud.githubusercontent.com/assets/705860/6456442/07d5a73c-c129-11e4-8ffb-e2e152c86622.png)

https://github.com/opengovfoundation/madison/blob/master/public/js/doc.js#L30

**Comment by cmbirk** [comment]
This is fixed in the 1.8 milestone
