### ISSUE TITLE
Clean up Sass directory

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#502]
Making notes here.  @krues8dr, would appreciate feedback:

Keep:
* `_variables.scss` contains all of our app-wide colors
* `_socials.scss` contains all styles regarding social shares or logins
* `_annotator.scss` contains custom styles specific to annotator
* `_animations.scss` contains style specific to madison animations
  * this may be better suited as included in a page-level .scss file

Cleanup:
* `style.scss` is a mess, but really should be used for app-wide styles

* `_directives.scss` was supposed to hold all styles necessary for our directives, but obviously that didn't happen

* `_rightbar.scss`, `_administration.scss`, `_dashboard.scss`, `_document.scss` should probably all be moved to page-level styles maybe?

* `_mixins.scss` I don't think we use most of these at the moment.  I would like to keep our mixins separated though.

* `screen.scss`, `print.scss`, and `ie.scss` are compass defaults and haven't been really used but `screen.scss` does import the compass reset

* `_helpers.scss` only has one class: `.centered`

**Comment by krues8dr** [comment]
I don't really see much reason to keep any of it if we're starting over from scratch.  A lot of it will be similar, but there's no real reason to keep most of these.  I'm in favor of a more atomic subfolder structure, like [what we did on State Decoded](https://github.com/statedecoded/statedecoded/tree/master/htdocs/themes/StateDecoded2013/static/scss).

**Comment by cmbirk** [comment]
I was mainly describing the structure.  I really like the way you guys did it in the StateDecoded though.  100% down with that.  I would like to keep external stylesheets in the `bower_components` directory though for ease of upgrade sake.

**Comment by krues8dr** [comment]
>  I would like to keep external stylesheets in the bower_components directory though for ease of upgrade sake.

[Yup, there's a hack for that.](https://github.com/krues8dr/krues8drdotcom-theme/blob/version-3/config.rb)

**Comment by cmbirk** [comment]
Awesome.  

What's the reason for the `.css.scss` extension here:

https://github.com/statedecoded/statedecoded/tree/master/htdocs/themes/StateDecoded2013/static/scss/dependencies/variables

**Comment by krues8dr** [comment]
![I dunno](http://i.imgur.com/jxgHzYQ.jpg)
