### ISSUE TITLE
"My Documents" page not loading properly 

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#506]
http://dev.mymadison.io/documents

![screen shot 2015-03-16 at 2 09 01 pm](https://cloud.githubusercontent.com/assets/6437336/6672950/0a1cfece-cbe6-11e4-8c71-515109e2867c.png)

**Comment by cmbirk** [comment]
Well that's ugly.  Thanks, it's an issue with the groups api.

**Comment by cmbirk** [comment]
The api route `/api/user/{user}/docs` is loading the groups incorrectly.
