### ISSUE TITLE
Nothing happens when I click "Submit" when creating a new group

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#508]
I need to know my information has been submitted.

**Comment by cmbirk** [comment]
This is most likely an issue with the `angular-growl` plugin.

**Comment by cmbirk** [comment]
@leilis I'm not able to reproduce this.  What steps did you take, and what did it show you?

**Comment by leilis** [comment]
@cmbirk that's strange, it's now working like it should. Earlier today if I signed in, clicked on "Want to create a group?" on the Group Management page, filled in some information, and clicked "Submit", nothing happened -- it didn't take me back to the groups page or show me the "Your group has been created!" message.

**Comment by cmbirk** [comment]
Interesting.  I'll keep an eye out for it, but closing this issue.
