### ISSUE TITLE
Unable to switch between using dev.madison.io as an individual doc sponsor and on behalf of a group in drop-down menu

### ISSUE THREAD

**Issue by leilis** [opengovfoundation/madison#509]
Even though I can see that I'm a member of three groups and can manage them through "My Groups"

**Comment by cmbirk** [comment]
I'm guessing the active group isn't being set through the API.  Thanks.

**Comment by cmbirk** [comment]
We need to load user group info when making the call to `/api/user/current` and this should persist through the SessionService.

**Comment by cmbirk** [comment]
Changing the `/api/user/current` route payload to:

```
{
  type: (user | group),
  user: {
    //Current user / group being used or posted as
  }, groups: {
    //All accounts that the user has access to
  }
```
...

Will still need to update Annotator any time this changes.

**Comment by cmbirk** [comment]
The current user payload looks like: 

```
user: {
  id: ...,
  email: ...,
  fname: ...,
  lname: ...,
  address1: ...,
  address2: ...,
  city: ...,
  state: ...,
  postal_code: ...,
  phone: ...,
  url: ...,
  created_at: ...,
  role: ...,
  activeGroup: ...,
  verified: ...
}
```

I'm making these changes: 

- [ ] change `role` to `admin` and make it a boolean
- [ ] add `independent_sponsor` boolean
- [ ] add `display_name` to be used in place of `fname` and `lname` in the current templates.  This will make it easier as we won't have to decide between showing those fields for users or display name for groups
- [ ] add `role` to each group payload

which means that our `routes.js` file will have to be updated, as it currently uses `role` for route permissions.

**Comment by cmbirk** [comment]
It's actually the `authService.js` `isAuthorized()` that needs updating.

**Comment by cmbirk** [comment]
Ugh.  This is being stored using `Session::put` and is only being used for document creation.

**Comment by cmbirk** [comment]
So I've changed the payload to:

```
{
  user: {
    id: ...,
    fname: ...,
    lname: ...,
    display_name: ...,
    ...
  }, groups: [
    {...},
    {...},
    ...
  ],
  activeGroupId: ...
}
```

**Comment by cmbirk** [comment]
Done.
