### ISSUE TITLE
Comments Don't Work on Doc Page

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#510]
http://dev.mymadison.io/docs/san-francisco-open-data-legislation-2014

![screen shot 2015-03-16 at 5 11 43 pm](https://cloud.githubusercontent.com/assets/2349231/6676593/8955da1c-cbff-11e4-89d1-a87b04aa3c32.png)

**Comment by cmbirk** [comment]
Just pushed the fix for this to the `dev` branch.
