### ISSUE TITLE
No Way to Clear Document Filters

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#511]
Tried undoing these filters with no way to do so, short of refreshing everything

![screen shot 2015-03-16 at 5 13 56 pm](https://cloud.githubusercontent.com/assets/2349231/6676652/ebd7f9cc-cbff-11e4-93ac-6727959ed5c7.png)

**Comment by cmbirk** [comment]
Ugh.  We've had this issue before, but I thought we had it resolved.

These `select2` elements are flakey.

**Comment by cmbirk** [comment]
For some reason, when you try to load the sprite `build/select2x2.png`, you're getting a 404.  @leilis and I are getting the sprite.  I have no idea why that would be the case.

**Comment by cmbirk** [comment]
Even after wiping the laptop we're still having this issue.  I'm at a loss.

My computer will allow navigation directly to the sprite, but the other will only show the Angular 404 page.  This might be an issue with the nginx media file permissions (?)!!

**Comment by cmbirk** [comment]
This has been removed on the new design.  Closing.
