### ISSUE TITLE
"Permalinks" refuse to work without index.php

### ISSUE THREAD

**Issue by philipjohn** [opengovfoundation/madison#517]
Having just installed Madison to play around I realised that URLs other than the home page weren't working.

http://reviewandcomment.org/ (click on the menu items)

However, all works fine by starting from http://reviewandcomment.org/index.php

I've verified that mod_rewrite is enabled and working but I can't fathom what is going on with Madison URLs.

Any clues?

**Comment by cmbirk** [comment]
That does sound like a mod_rewrite issue.  What are you seeing in your `public/.htaccess` file?

Also, make sure that you have `AllowOverride all` in your `httpd.conf` to ensure that .htaccess file is used correctly.

**Comment by krues8dr** [comment]
Just to clarify, `AllowOverride all` has to be set *for the path to the web root for the site*.  There are several instances of `AllowOverride` in a stock setup.

**Comment by krues8dr** [comment]
Aside from that, you might also make sure that the conf is properly setting `DirectoryIndex index.html index.php`, and that `Indexes` are on (e.g. `Options +Indexes` or `Options All`) for the `Directory` in question.

**Comment by philipjohn** [comment]
:boom: Fixed it.

Added this to my apache2.conf:

```
<Directory /var/www/dir/to/madison/public/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```

Thanks folks!
