### ISSUE TITLE
Incorrect password error message

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#521]
`Email address or password is incorrect`

This is frustrating.  If the email's in the system, tell the user that their password is incorrect.  Otherwise tell them that the email address isn't recognized.

**Comment by krues8dr** [comment]
Just to give the historical viewpoint here, traditionally this is done to avoid exposing matching email addresses and allowing brute forcincg

**Comment by cmbirk** [comment]
Yeah, I get that, but the user is most important here.

**Comment by krues8dr** [comment]
:+1: Agreed.
