### ISSUE TITLE
Clean up routes

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#524]
Separate out routes into groups like 

http://laravel.com/docs/5.0/routing#route-groups

and make each group a separate file in `/app/routes/` which will get automatically included in the `routes.php` file via the include loop at the top of the file.

**Comment by krues8dr** [comment]
@sethetter Just making you aware of this issue for your current work on cleanup.

**Comment by sethetter** [comment]
Seems like a solid pattern to adopt! I'll assign it to me and handle it once I wrap up these other couple things.

**Comment by krues8dr** [comment]
Mostly done as of 3.0
