### ISSUE TITLE
Allow 'Featured' documents

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#527]
This needs to be accessible via the `/api/docs/featured` endpoint via #522 .

We need a flag that is set to allow a document to be 'Featured' on the home dashboard.  If another document is already featured, it should show a message asking the user if they're sure and informing them that the other document will become 'un-featured'.

We also will need the ability to upload images for each document.  Regular documents may / may not have an image associated with them, but a featured image must.

Here's how I'm seeing this working:

- [x] create a `settings` table that has a row for `featured_doc` that we can seed.  This will also allow us to set up site-specific preferences down the road.
- [x] create a `images` directory in the `storage` directory
- [x] create a subdirectory in `images` for each document *on image upload*.  This is to store multiple versions of the document image in various sizes using something like imageMagick
- [x] create a subdirectory in `images` called `default` that will hold a few default images.  This directory will need to be added to the repo.
- [x] Allow the user to upload an image for each document or select from the list of defaults in the repo.  This should be added to the document dashboard page.
- [x] Include a link to the image as an attribute on the Doc when it's serialized which can be displayed on the front-end

**Comment by cmbirk** [comment]
Done in issue 477 branch, commit 106346f

**Comment by cmbirk** [comment]
Re-opening this due to some design flaws.

We need a document summary / introtext for the Featured Document design.  Using the first N words for a legal document is worthless, as you'll get the same legal introduction for most documents.  

Users also will be used to getting a readable introduction / summary here, and it will throw people off if they see the largest text block on the homepage as unreadable legalese.

For these reasons, I'm going to enforce a Featured Document have an introtext.  This also means a Featured Document will always be set.  I'll default the DB seed to set one on installation.  I'm also going to make a couple UI changes so that this process is a bit more understandable, including:

- [ ] Change the 'Featured Document' checkbox to a button that is muted when the document is featured. There won't be any removing, you'll just have to set a different document.
- [ ] Show a modal on error if the admin doesn't have the image / introtext set when trying to set a document as Featured instead of the growl notifications we currently have set up.  It will have a small explanation of why we need the introtext / image and how to use the default image included in the repo.
- [ ] Add a small link next to the image uploader that allows the author to set our default image included in the repo as the document thumbnail.

And potentially:

- [ ] Add a select2 element to the 'Settings' admin page that will show all of the documents that are currently eligible for being Featured ( has image / introtext ).  That way if the admin is just looking to plug something in there they have all of their available options.

**Comment by cmbirk** [comment]
I've been convinced otherwise by @krues8dr .  Because the admins are the only role that is allowed to feature documents, they can enforce business constraints if they so choose.

For the authors, we'll add prompts suggesting they add an image / summary.

I think I'll still add the select2 element on the 'Settings' page with filters so that the admin can search for documents with images / with summaries so it's a bit easier on their side.

We'll still be enforcing a Featured Document be set as well and seed on installation.  That way there's still a default, but it's just explicitly set.

**Comment by cmbirk** [comment]
@krues8dr this means that we'll have to conditionally handle this information on the front-end

**Comment by krues8dr** [comment]
Way ahead of you. ;)

**Comment by cmbirk** [comment]
This is complete *without* the prompts in 3edb640.  This has been merged into `redesign` and pushing it up to `dev`.  Working on the prompts next.

**Comment by cmbirk** [comment]
Closing this in favor of #556 , which will handle the prompts.
