### ISSUE TITLE
Composer.json "zizaco/entrust": "dev-master" don't support laravel/framework v.4.1.25

### ISSUE THREAD

**Issue by zaenulhilmi** [opengovfoundation/madison#528]
I've try to install composer.json but then i found a problem, zizaco/entrust don't support illuminate/support 4. 
I think composer.json need to be updated, instead of using "zizaco/entrust": "dev-master", use other version that work

**Comment by zaenulhilmi** [comment]
so does package from roumen that has "dev-master" version in it.

**Comment by cmbirk** [comment]
@zaenulhilmi you are correct.  We are currently working on a branch with fixes for this issue.  I will update here when we get the `issue477` branch merged.

**Comment by neetin** [comment]
I am also stuck on installation with this error. It is fixed? please update.

**Comment by krues8dr** [comment]
This was fixed a while ago.
