### ISSUE TITLE
Create document, but can't find created document (there are no documents on the list)

### ISSUE THREAD

**Issue by zaenulhilmi** [opengovfoundation/madison#529]
I create some documents by admin credential but there are no list of documents that I can see when i've done creating them on http://localhost/madison-master/public/documents or http://localhost/madison-master/public/dashboard/docs .

I've checked the database,those documents has been save on docs table, doc_contents, and doc_users table. 

I also see in C:\xampp\htdocs\madison-master\app\views\documents\list.blade.php (on my local computer) the else statement of "@if(Auth::user()->hasRole('Independent Sponsor') || Auth::user()->groups()->exists())" is the one that get executed. 
I don't know what is that mean. Should I make a group first? or should I be an Independen Sponsor first? Well, I can not do both. Link to request Independen sponsor and create group is broken.

**Comment by zaenulhilmi** [comment]
Solved. Sorry, my bad. I didn't make a virtual host. That's why links get broken and there are a lot of feature that doesn't work. 
Thanks.. I'll be more carefull next time before i create an issue. :))

**Comment by cmbirk** [comment]
No worries @zaenulhilmi, thanks for the heads up.  I should have had that better documented.  I'll make sure to add that!
