### ISSUE TITLE
Create document without filling the title will land to a blank page

### ISSUE THREAD

**Issue by zaenulhilmi** [opengovfoundation/madison#530]
When I try to create document on dashboard using a blank title (link in my environment: http://madison-dev.dev/dashboard/docs), it will show a blank page. 

die($validation); on master/app/controllers/DashboardController.php at line 233 has something to do with it. Get rid of die($validation); on line 233 will fix this.

**Comment by cmbirk** [comment]
It *should* return an error if the document title is blank.  That is a required field.

Thanks for letting us know, I'll take a look.  *Pull requests are always welcome* ;)

**Comment by zaenulhilmi** [comment]
I've sent a pull request. It is my FIRST pull request, so If there's something wrong or something that I need to do, please tell me. :)

**Comment by cmbirk** [comment]
@zaenulhilmi thanks for the pull request!  I've merged it and will close this issue :)
