### ISSUE TITLE
Create install script

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#531]
A basic cli interface / script for installation would be very useful to a bunch of people.

Step by step dependency installations, setup instructions, etc.

*To be continued...*

**Comment by schlos** [comment]
(+1)

**Comment by nephop** [comment]
Yes, I am trying to use this project from last 2 days and I am unsuccessful to use this in local host or hosted server is there any guidelines..... Can some one help.

**Comment by cmbirk** [comment]
@nephop Our [1.8 milestone](https://github.com/opengovfoundation/madison/milestones/1.8) has a much easier installation and much more extensive documentation.  Milestone 2.0 will come with a comprehensive install script.  The `dev` branch right now has all of the work from the 1.8 milestone in it, and we're finishing up the remaining issues as fast as we can.  You can take a look at our [initial documentation](madison.readthedocs.org) for the upgrade notes.

**Comment by krues8dr** [comment]
Pushed to 3.1.  After we break apart the app for the 3.0 release and resolve our asset pipeline issues, we should be in a good place to do this work.

**Comment by sethetter** [comment]
This is somewhat addressed with #1013 and #985. Anything more we want to consider here? Or good to close?

**Comment by krues8dr** [comment]
Yeah, I think once that work is done and shipped this will be good to close.
