### ISSUE TITLE
Missing FontAwesome Fonts

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#537]
`Resource interpreted as Font but transferred with MIME type text/html: "http://local.mymadison.io/fonts/fontawesome-webfont.woff?v=4.2.0".`

**Comment by cmbirk** [comment]
Looks like it's coming from lines 9-10 in `bower_components/font-awesome/css/font-awesome.css` which compiles to 

```
src: url("../fonts/fontawesome-webfont.eot?v=4.2.0");
  src: url("../fonts/fontawesome-webfont.eot?#iefix&v=4.2.0") format("embedded-opentype"), url("../fonts/fontawesome-webfont.woff?v=4.2.0") format("woff"), url("../fonts/fontawesome-webfont.ttf?v=4.2.0") format("truetype"), url("../fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular") format("svg");
```

on lines 26-27 in style.css

**Comment by krues8dr** [comment]
Fixed in #c52a0d408dc7f849a0e7b6ebc4e49e0cf8c06de2

**Comment by cmbirk** [comment]
@krues8dr It will pull the commit in if you leave out the hash.  And you actually only have to put in the first 7 characters.

**Comment by cmbirk** [comment]
Testing c52a0d4
