### ISSUE TITLE
Dropdown broken on mobile

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#541]
Clicking the hamburger icon triggers the DOM changes for the dropdown, but it isn't displayed.

**Comment by LouisMilotte** [comment]
I'm unable to reproduce with Galaxy S5 via chrome (version 42.0.2311.11)  on android (version 4.4.2). The referenced issue #348 mentioned iOS; is this the only OS encountering this issue?

**Comment by cmbirk** [comment]
I'm still getting this issue on chrome for iOS.

**Comment by barryvdh** [comment]
I'm also experiencing this, the navbar doesn't seem to work. Any ideas?
The collapse state does seem to change, but it doesn't show any different. Test in Chrome/safari on mac, and my Android Chrome browser

**Comment by barryvdh** [comment]
Can you verify that #678 fixes the problems for you?

**Comment by krues8dr** [comment]
:+1: Nice work!  Thanks for this!
