### ISSUE TITLE
Remaining Redesign Tasks

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#542]
- [x] Login page
- [x] Social login buttons
- [x] MyDocuments page
- [x] Links ( black on white background can't tell they're links )
- [x] Admin documents list page
- [x] Document editing page
- [x]  Anchor footer to the bottom of the page ( short pages such as login the footer creeps up into the page )
- [x]  Sub-dropdown needs some love ( See below )

**Comment by cmbirk** [comment]
I changed the default link color, so some other links are going to have to be adjusted, such as the homepage document links.

**Comment by cmbirk** [comment]
@krues8dr Just a couple tweaks that I'm wondering about in this commit: d9a940b .

It seems to be missing the fa-eye icon and I had to pixel push the Save Now button.  Would you take a quick look and let me know if something seems obviously off?  The commit has been pushed up to our dev server.

**Comment by krues8dr** [comment]
Most of the links aren't blue, they're black.  So perhaps we should consider reverting to the original black instead of having to override them on 90% of the site?

**Comment by krues8dr** [comment]
Also, it doesn't make sense to be doing the design work on two different branches, we need to pick one and go with it.  IMHO, `dev` should be pulled from `redesign`, so that `dev` is kept low-noise.

**Comment by krues8dr** [comment]
I'm not sure what is being served there, but the font file for font awesome should be around 64kb, not the 1.7kb that is being pushed there?  Not sure how that happened.  If you merge in my changes from the past week you'll get the fix to the font path that should resolve this (from c52a0d408dc7f849a0e7b6ebc4e49e0cf8c06de2 ).

**Comment by krues8dr** [comment]
It looks like the changes you made to `dev` aren't up, or have been replaced, because there are a lot of issues on the edit page for vertical rhythm right now, and I'm not seeing any styling on the save button. LMK when that's fixed up and I'll have another look?

**Comment by cmbirk** [comment]
@krues8dr ok, that works.  I'll start working directly on the redesign branch.  I thought I pushed everything to dev, but I'll double check this afternoon.

**Comment by cmbirk** [comment]
On the link colors, sure.  I was only seeing the document titles as black links, but must have not done my due diligence... :|

My issue is any text not explicitly styled will lose link recognition.  We've already explicitly styled headers, navs, etc. so we can add their colors there.  Therefore we'd have to explicitly style new content pages, document pages, annotations, comments, blocks of text, etc., instead of design items we're already focusing on.

I'm not extremely attached to that notion, so if you still think setting the default as black is best, I can cede.

**Comment by krues8dr** [comment]
I think I'll cede here.  It's far easier to manage `h1,h2,h3,h4,h5,h6 { a { } } ` than the other way around.  Blue it is!  I'll make the change on my end to deal.

**Comment by cmbirk** [comment]
- [ ] Anchor footer to the bottom of the page ( short pages such as login the footer creeps up into the page )

**Comment by cmbirk** [comment]
Sub-dropdown needs some love:

![dropdown-design-issue](https://cloud.githubusercontent.com/assets/764851/7354895/4f4cc200-ecec-11e4-99c1-41cee896b6d8.png)

**Comment by cmbirk** [comment]
The second tab of the admin document editor page is off by a couple pixels and I'm not sure why.  Revising later...

**Comment by cmbirk** [comment]
And it cascades a bit down the page:
![edit_document](https://cloud.githubusercontent.com/assets/764851/7355606/fa5dcb9a-ecf0-11e4-8b65-7e0bc31bdac4.png)

**Comment by cmbirk** [comment]
Dropping the sticky footer for now.  Going to take a bit of moving around that will complicate things at the moment, and *only* fixes a few pixels on the login page at the moment.
