### ISSUE TITLE
Set up routes for homepage / dashboard

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#543]
Proposed:

Dashboard / Home Page: `/`
Landing Page: `/introduction`

@seamuskraft @leilis does that work for everyone?

Keep in mind the `/introduction` link will be this page: 

https://github.com/opengovfoundation/madison/wiki/Redesign#homepage

sent out for introductory / marketing purposes.

**Comment by leilis** [comment]
Looks good to me!

Leili Slutz
Operations Architect
The OpenGov Foundation <http://www.opengovfoundation.org>
leili@opengovfoundation.org
614-424-9185

**Comment by seamuskraft** [comment]
Looks good.  Thanks.

- Seamus  ————

Seamus Kraft 

Executive Director & Co-Founder
The OpenGov Foundation 

P: 760-659-0631
OpenGovFoundation.org 

————

2014/2015 Shuttleworth Fellow

**Comment by cmbirk** [comment]
@krues8dr do we have this page built out or are we waiting on anything for it?

**Comment by krues8dr** [comment]
Nope, we need the content I guess?

**Comment by cmbirk** [comment]
K.  I have the designs for it here:

https://github.com/opengovfoundation/madison/wiki/Redesign#homepage

@seamuskraft @abartnick we'll need content to replace the dummy content for that page.

**Comment by cmbirk** [comment]
@seamuskraft @abartnick any word on this?
