### ISSUE TITLE
Duplicated password hashing on Password Recovery

### ISSUE THREAD

**Issue by rodowi** [opengovfoundation/madison#545]
@codemoe pointed out that there might be a bug in the password resetting code, due to an additional Hash::Make being invoked in RemindersController.

We can just remove that invocation. Password hashing is already done in the User model.

Might be related to #482 

The discussion: https://github.com/mxabierto/madison/pull/212#issuecomment-95636247

**Comment by codemoe** [comment]
The PR with the changes needed for the fix is https://github.com/mxabierto/madison/pull/218

**Comment by rodowi** [comment]
on it, solving conflicts

**Comment by cmbirk** [comment]
Thanks for catching this.  I'll get this merged!
