### ISSUE TITLE
Redesign: Annotations

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#559]
Per John's designs.

**Comment by krues8dr** [comment]
@cmbirk Can users vote on comments in annotations?  I'm not seeing it in the old code, but it's in the design.

**Comment by cmbirk** [comment]
@krues8dr we didn't have that in the old designs because we wanted to keep the comment stream chronological so that the conversation didn't become disjointed.

We can certainly add them for the new designs, but the comments shouldn't re-order.

**Comment by krues8dr** [comment]
I don't know that it's a priority, but the filters on the annotation side pane make a little less sense without them.  They'll only apply to annotations, and that's only useful if lots of annotations are in the same block. It's really more of a nice-to-have.  Tempted to punt on this for now and open a new known issue.

**Comment by cmbirk** [comment]
I'm fine with that.  I don't want that to hold up this release, and the annotations are definitely the primary focus here.

That being said, we'll want to have this functionality for the 'Discussion' tab, so it may be not be a big lift above that.
