### ISSUE TITLE
Problem with datetime picker

### ISSUE THREAD

**Issue by urkonn** [opengovfoundation/madison#563]
When editing the document information the datetime picker behaves strange in Firefox

![selection_026](https://cloud.githubusercontent.com/assets/37691/7761620/8ccb637a-ffed-11e4-9a5a-964864e058b1.png)

Possibly it's a bug in moment.js

![selection_029](https://cloud.githubusercontent.com/assets/37691/7761861/2cb66dbe-fff1-11e4-84d9-c2a803992225.png)

**Comment by cmbirk** [comment]
Thanks @urkonn .  I'll take a look.  We were having some issues with moment.js earlier.

**Comment by rodowi** [comment]
Might be caused by FF ignoring the dashes '-'

http://stackoverflow.com/questions/19839819/moment-js-returning-nan-in-firefox-but-not-chrome

Weird because iso8601 actually enforces dashes
http://en.wikipedia.org/wiki/ISO_8601

**Comment by sethetter** [comment]
New UI in v4
