### ISSUE TITLE
Login box oddly shaped & positioned

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#564]
Inconsistently appears wherever the user has clicked. We should float it at the front-center.

**Comment by cmbirk** [comment]
This was originally done to meet action expectations.  ie.  If someone selects a piece of document text, they're expecting an annotator selection window.  We were keeping the window placement / popup event consistent, but displaying the login content instead.

If we want to go away from that interaction toward a modal, we're going to want a screen takeover to change user focus and drive focus to the login modal.

**Comment by cmbirk** [comment]
We're going to need to revisit this, and it's probably worth poking @boboroshi for.

We can't have a screen take-over for login for people selecting text on the document.  If they're attempting a simple copy-and-paste, this would be extremely frustrating.  I'm leaning toward reverting these changes back to the functionality we had before.  If the `loginPopupService` is behaving correctly, this shouldn't be an issue.

**Comment by krues8dr** [comment]
This happening on copy-paste is a different issue, and should be opened accordingly.  This issue is purely a design one.
