### ISSUE TITLE
UI review

### ISSUE THREAD

**Issue by boboroshi** [opengovfoundation/madison#569]
![mad_rev_1](https://cloud.githubusercontent.com/assets/2223/8235273/06abd3ec-15af-11e5-9fb3-bc2b9c5f59dd.png)
![mad_rev_2](https://cloud.githubusercontent.com/assets/2223/8235275/06ef7804-15af-11e5-8d5c-7b0856a6ff80.png)
![mad_rev_3](https://cloud.githubusercontent.com/assets/2223/8235276/06f761ae-15af-11e5-8186-f4dc6c4d2a43.png)
![mad_rev_4](https://cloud.githubusercontent.com/assets/2223/8235274/06c09f84-15af-11e5-8489-de0aac3b95ff.png)

**Comment by krues8dr** [comment]
@boboroshi Here's what I've got for the documents page header, lmk if that border/spacing needs more work:

![screen shot 2015-06-23 at 1 09 55 pm](https://cloud.githubusercontent.com/assets/127904/8312187/3d622aa0-19a9-11e5-9f72-999fa69c4760.jpg)

**Comment by boboroshi** [comment]
Better. Needs more space above the main headline, the sponsored by should be centered in that space between the lines and a little larger. Buttons looking much better.

**Comment by krues8dr** [comment]
That should be everything except the numbers and bullets issue.  We don't really have a good way of knowing if the sections are already numbered when that list is created, and it doesn't look quite right without the bullets, imho.
