### ISSUE TITLE
Sign Up Link in Yellow Banner Doesn't Work/Link to Anything

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#571]

**Comment by cmbirk** [comment]
I'm not sure what this is referring to.

**Comment by seamuskraft** [comment]
Screen shot attached (link in the green bar at the top).

[image: Inline image 1]


- Seamus

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation <http://OpenGovFoundation.org>
Ph: +1-760-659-0631
Tweet Us @FoundOpenGov <http://twitter.com/foundopengov>

**Comment by cmbirk** [comment]
I think you have to upload those via GH.  It doesn't look like your attachment made it through.

**Comment by seamuskraft** [comment]
![screen shot 2015-06-22 at 3 35 06 pm](https://cloud.githubusercontent.com/assets/2349231/8291151/a4a6f2a4-18f5-11e5-8227-c3606e87b56b.png)
