### ISSUE TITLE
About page: no way to submit questions

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#572]
"Still have a question? Let us know on the left. We'll get back to you right away."

There is nothing on the left we can use to ask a question.

**Comment by krues8dr** [comment]
Hmm.  UserVoice doesn't exactly fit here as we were using it previously.  I really don't want a drawer on top of a drawer.

**Comment by cmbirk** [comment]
There are a couple different solutions there I think.  I believe we execute the modal using a link, and they have some new interfaces we can plug in.  I'll take a look and post back here.

**Comment by cmbirk** [comment]
I've found a different Uservoice widget that we can use for this.  @krues8dr the question here is how to conditionally include a uservoice script, as we won't have this in dev / local environments.

**Comment by krues8dr** [comment]
Post a link to the widget and maybe I can come up with something. ;)

**Comment by cmbirk** [comment]
Closing this in favor of #593 .
