### ISSUE TITLE
Annotations Out of Place on Document

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#573]
See the annotations floating up in the top right hand corner of the page.  Screen shot attached.

![screen shot 2015-06-22 at 2 19 31 pm](https://cloud.githubusercontent.com/assets/2349231/8289322/c4fe84ce-18e9-11e5-8486-95de4888b47c.png)

**Comment by krues8dr** [comment]
O_O

**Comment by krues8dr** [comment]
Fixed with previous fixes.

**Comment by krues8dr** [comment]
This particular instance is actually a detached annotation, which needs special handling that's not currently in place.

**Comment by krues8dr** [comment]
Hmm.  Now it's fixed again.  Feel free to reopen if it's still broken.

**Comment by krues8dr** [comment]
This is most likely a race condition on adding annotations, but I've beaten that code to death and can't find it.  I also can't reproduce this.

**Comment by krues8dr** [comment]
This happens reliably when opening a document and then navigating to a different document.

**Comment by cmbirk** [comment]
Are we still seeing this issue?  I think this was fixed in #701.  It was a matter of detached annotations after a document was changed.  I think #654 is still in play.

**Comment by krues8dr** [comment]
@cmbirk I think you're right - the symptom is the same for both, but the reason is different.

**Comment by cmbirk** [comment]
Ok.  I'm going to close this one and prioritize #654.
