### ISSUE TITLE
Annotation Window Broken on Document

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#574]
When hovering over a previously-made annotation (attempting to copy the annotation link), the annotation box/window disappears.  Happens right when my mouse gets to the "copy annotation link."

![screen shot 2015-06-22 at 2 22 10 pm](https://cloud.githubusercontent.com/assets/2349231/8289423/52d53aae-18ea-11e5-9e58-ebe59cb9b950.png)

**Comment by cmbirk** [comment]
This is fixed in 31276c9
