### ISSUE TITLE
No Way to See A Comment Has Been Made on Another User's Annotation/Comment

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#576]
The "comments" bar appears at the bottom, but it isn't clear if there are any comments lurking beneath.  Perhaps add a number to signify how many comments are threaded therein?

![screen shot 2015-06-22 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/2349231/8289502/d4e645ba-18ea-11e5-9a11-a265c5369c0b.png)

**Comment by cmbirk** [comment]
@seamuskraft the comments bar doesn't appear unless there are comments.  Looking into the comment count.

**Comment by cmbirk** [comment]
This is going to require complexity in the Annotator plugin that we don't want to tackle at the moment.  Will revisit when we re-work the Annotator setup with V.2.
