### ISSUE TITLE
FAQ page copy

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#578]
What is Madison?
Madison is a free tool that helps elected officials and everyday Americans solve problems together. Elected officials post drafts of policy documents on the site so that you can weigh in and stay informed about the issues you care about most. Madison brings policymaking out into the open, and gives you a voice in your government and a way to hold it accountable.

How can I use Madison to be heard on the issues I care about most?
Government policy covers a huge range of issues that directly impact you, your family, and your place of work--from where you can park your car, to where your kids go to school, to how much you pay in taxes. To find a bill on a topic you care about, simply search Madison with keywords, councilmembers’ names, or document status. Then sign up for an account to vote, add general comments, ask questions, and suggest changes directly to these new laws, rules and regulations.

How do I annotate a document in Madison?
Thanks for asking! We’ve made you a helpful video showing you how it’s done. (It’s super easy!)

How can I get help with a Madison issue or question?
To report a technical issue or suggest new Madison features or documents to add, please use the “Feedback and Support” tab on the left-hand side of every web page.

To ask questions about Madison or your user account, send us an email at sayhello@opengovfoundation.org. We’d love to hear from you!

To raise a question about a document in Madison, just sign up and add it directly to the document and the debate.

How can I add documents to Madison?
Once you have signed up for Madison and have a username and password, please email us at sayhello@opengovfoundation.org to request an admin account in order to add new documents to Madison.

How do I know if my Madison comments and suggestions are read by my local elected officials?
When a document sponsor reads your comment, question or annotation, you will instantly receive both an email notification and a Madison notification.

What is a verified Madison user and how do I become one?
A verified user is someone who has proven that they are a real human being, or a real representative of a real organization. Being a verified user gives your activity on Madison a little more weight--for example, by showing an elected official that you’re an actual constituent, or by demonstrating that you are an expert in a pertinent field.

Request verification at the bottom of your profile page.

Who runs Madison?
Madison is free, open source software created by The OpenGov Foundation, a nonpartisan, nonprofit 501(c)3 based in Washington, DC. We build tools to better connect you with your government officials, help you hold them accountable, and make sure your government is working for you and your family. We just handle the technical side of Madison; any policy posted on the site comes directly from government officials or other users.

How can I support the growth and improvement of the Madison community?
Join the Madison community! Contribute your suggestions to policy documents, interact with other users, and suggest improvements and changes to the site itself.

Keep in touch--sign up for news and updates on Madison.

Contact your elected officials. Madison is built for democracies everywhere, at any level of government. Spread the word!

If you’re a developer, fork Madison on Github.

How can I bring Madison to my local and state government?
Drop us a line at sayhello@opengovfoundation.org, and we can help you start a Madison community in your city or state.

**Comment by cmbirk** [comment]
@abartnick This is a great start.  I'll have to update some of the process stuff and add relevant links.  What video are you referencing in the 3rd paragraph?

**Comment by abartnick** [comment]
The video was part of the pre-existing copy; I only made very basic grammatical/spelling changes.



—
