### ISSUE TITLE
No Way to Reply to General Comment Made on Entire Document

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#579]
The comment went through, but there's no way to reply to it.

![screen shot 2015-06-22 at 2 31 44 pm](https://cloud.githubusercontent.com/assets/2349231/8289610/8912b172-18eb-11e5-9c92-b6104cae56d4.png)

**Comment by krues8dr** [comment]
This also resolves annotations that have multiple highlights not showing up properly.
