### ISSUE TITLE
Unable to Request Account Verification

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#581]
When I first visited my account page, it already said that my request was pending.  I tried to request account verification anyway, and I got some sort of error.  Unable to see what the error is, though...just got some red thing pop up in the top right corner (See screenshot attached).

![screen shot 2015-06-22 at 2 34 53 pm](https://cloud.githubusercontent.com/assets/2349231/8289718/3d64bc9c-18ec-11e5-9c09-6888a129c57b.png)

And here is what the page looked like when I first logged in.  You can see that the "request was pending" before I requested verification.

![screen shot 2015-06-22 at 2 38 33 pm](https://cloud.githubusercontent.com/assets/2349231/8289739/61e53e52-18ec-11e5-85b0-7eb6d9cd66a9.png)

**Comment by cmbirk** [comment]
Just an FYI @seamuskraft, those are two separate requests.  Your Independent Sponsor request was pending, but you hadn't yet requested to be a Verified Account.  

Still looking into the Verified Account error.
