### ISSUE TITLE
No links on page footer

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#582]
Cannot click through to "For Citizens," "For Authors," or "For Developers"
![screen shot 2015-06-22 at 2 37 13 pm](https://cloud.githubusercontent.com/assets/12156643/8289730/58f541ca-18ec-11e5-9380-a97fb8197ce2.png)

**Comment by cmbirk** [comment]
I'm not sure what these should be linking to.

**Comment by krues8dr** [comment]
I'm not sure these are supposed to be links.  I think it's just taglines.

**Comment by cmbirk** [comment]
I think we can deep link to the sections on the homepage for this.

**Comment by cmbirk** [comment]
This is dependent on #543

**Comment by cmbirk** [comment]
These are all on the same scroll level, so I'm just going to link to `/intro` for these
