### ISSUE TITLE
Can't click to comments or annotations on most active legislation

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#586]
http://dev.mymadison.io/
![screen shot 2015-06-22 at 2 44 34 pm](https://cloud.githubusercontent.com/assets/12156643/8289905/57d76664-18ed-11e5-9c25-bd16f59b9fcc.png)

**Comment by cmbirk** [comment]
Those are just showing the activity.  I'll link those to the document as well.

**Comment by cmbirk** [comment]
After playing around with this a bit, it doesn't really fit with the designs.  I think the title of the document is fine being linked.  Closing.
