### ISSUE TITLE
Unable to Request Ability to Be Independent Document Sponsor/Author

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#587]
See attached screen shot

![screen shot 2015-06-22 at 2 45 37 pm](https://cloud.githubusercontent.com/assets/2349231/8289922/69a9f1c2-18ed-11e5-8cf7-7e28cf8e8655.png)

**Comment by cmbirk** [comment]
Looks like this page is just missing.  Adding...

**Comment by cmbirk** [comment]
This has been fixed.
