### ISSUE TITLE
"See previously featured legislation in the archive" button broken

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#588]
http://dev.mymadison.io/
![screen shot 2015-06-22 at 2 46 04 pm](https://cloud.githubusercontent.com/assets/12156643/8289935/84e5e090-18ed-11e5-8f72-b74ebd86d41c.png)

**Comment by cmbirk** [comment]
We're not currently storing previously featured legislation.  I'll have to create a table for this to keep track of what's been featured.

Proposal:

**Table: featured_archive**
id: incrementing
doc_id: <doc_id>
set_featured: (date was set as featured) //Currently not tracking this.
removed_featured: (date was removed as featured)

This will have an entry for every time the featured document is changed.

@krues8dr seem sane?

**Comment by krues8dr** [comment]
That's not a button, that's a header.  We should just change the header.

**Comment by krues8dr** [comment]
I'm messing with that now, so I'll go ahead and change it.

**Comment by krues8dr** [comment]
![screen shot 2015-06-23 at 12 42 08 pm](https://cloud.githubusercontent.com/assets/127904/8311598/4a456c36-19a5-11e5-839d-a28a084569e2.jpg)

Here's my proposed fix.

**Comment by cmbirk** [comment]
Per our convo, I think 'Active Legislation' covers it.
