### ISSUE TITLE
Can't select tags

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#589]
http://dev.mymadison.io/
![screen shot 2015-06-22 at 2 47 19 pm](https://cloud.githubusercontent.com/assets/12156643/8289952/a19ea212-18ed-11e5-888d-86708e7f9b58.png)

**Comment by abartnick** [comment]
Tags also not viewable on bill page.

**Comment by cmbirk** [comment]
We don't have the tags on the document page anywhere in the designs.

**Comment by cmbirk** [comment]
For the tag filter, I propose something like the attached.  Does that work @boboroshi?

![tag filter](https://cloud.githubusercontent.com/assets/764851/8311977/fc964d18-19a7-11e5-88b5-a18bc12231ec.png)

**Comment by cmbirk** [comment]
This is done in 69548f0
