### ISSUE TITLE
Hitting 'enter' does not post comments

### ISSUE THREAD

**Issue by abartnick** [opengovfoundation/madison#592]
http://dev.mymadison.io/docs/foia-reform
![screen shot 2015-06-22 at 2 50 14 pm](https://cloud.githubusercontent.com/assets/12156643/8290006/11194ee4-18ee-11e5-8361-f16a5a167b2d.png)

**Comment by cmbirk** [comment]
This is probably posting on click instead of form submit.  Thanks.

**Comment by krues8dr** [comment]
Users are actually complaining about this on annotations.  Punting.
