### ISSUE TITLE
Annotator missing like / dislike / flag icons

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#594]
In the Annotator window.  Probably due to the glyphicon -> FA change.

**Comment by cmbirk** [comment]
Yep.  And can't just change classes, because I'm a moron and used `.glyphicon` as a selector...

**Comment by cmbirk** [comment]
@krues8dr I noticed the selector for the annotation sidebar actions is `.annotation .thumbs-up` for these.  I'm going to move those stylings to just `.thumbs-up` for use in the annotator-viewer.

**Comment by krues8dr** [comment]
:+1:

**Comment by cmbirk** [comment]
This is done in d6ae6d0
