### ISSUE TITLE
Create new secret key on deploy

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#60]
`php artisan key:generate`

**Comment by cmbirk** [comment]
Not sure if the artisan command is the best option here, but should be addressed.

**Comment by cmbirk** [comment]
Closing this as out of scope.

**Comment by krues8dr** [comment]
Just as an aside, if we create a new key on every deployment, everyone will be logged out of their session because the old key will be invalid.  Probably not a good idea.

**Comment by cmbirk** [comment]
aha.  That's a good point as well.
