### ISSUE TITLE
Need loading indicators

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#602]
Just adding a quick note here.  Things like the homepage document list need loading indicators.  We'll probably need to do a quick inventory here.  Annotations will need them as well.

**Comment by cmbirk** [comment]
The homepage pagination makes this less of an issue there.  The annotations are going to be a bit tricky I think because you can't just check the annotations length.  It needs to show the 'No Annotations' message if there are no annotations.

**Comment by sethetter** [comment]
One approach could be making sure all remote data fetching for a page happens in one method, and to set a loading flag that is flipped once all data is loaded. Until that point, we could just do a light grey overlay on the page with a loading spinner or something?

Doing piecemeal loading indicators might look better though. Thoughts?

**Comment by sethetter** [comment]
Done in v4!
