### ISSUE TITLE
Account creation banner is really hard to read

### ISSUE THREAD

**Issue by waldoj** [opengovfoundation/madison#607]
![madison](https://cloud.githubusercontent.com/assets/656758/8603344/8a1b15de-2645-11e5-8a7d-24a8475d88d9.png)

This hurts my brain.

**Comment by boboroshi** [comment]
How about either of these? I'm leaning towards blue as orange really screams on the page with that much of a wash.

<img width="682" alt="screen shot 2015-07-10 at 8 40 07 am" src="https://cloud.githubusercontent.com/assets/2223/8618796/5f9233f2-26df-11e5-9298-9753b5688a47.png">
<img width="683" alt="screen shot 2015-07-10 at 8 40 23 am" src="https://cloud.githubusercontent.com/assets/2223/8618797/5f9a23be-26df-11e5-8d24-f4ee6411b988.png">

**Comment by krues8dr** [comment]
+1 for blue.  Orange might be nice for errors though, later.

**Comment by boboroshi** [comment]
https://camo.githubusercontent.com/e4843d27745055ef4c67e71bcc0e7d6e0714fc2a/687474703a2f2f696d616765732e73696d706c7973796e646963617465642e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031342f30372f6d616b652d69742d736f2d6361707461696e2e6a7067

**Comment by sethetter** [comment]
3a27bf0
