### ISSUE TITLE
Can't Create New Document

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#608]
Trying to create a new document and it says that I did not enter a title...but I did: "US Code Title 17 - Copyrights."  

I put the doc title in:
<img width="1400" alt="screen shot 2015-07-14 at 6 25 58 pm" src="https://cloud.githubusercontent.com/assets/2349231/8686608/d9ad5832-2a55-11e5-838d-38d13ed396eb.png">

But get this error:

<img width="1405" alt="screen shot 2015-07-14 at 6 26 19 pm" src="https://cloud.githubusercontent.com/assets/2349231/8686615/e1b23e80-2a55-11e5-8bdb-cf6e5eb8ef5f.png">

**Comment by cmbirk** [comment]
@seamuskraft thanks for flagging this.  I expect it's an issue with the title having the dash in it, but I'll check it out.
