### ISSUE TITLE
Failed to Create New Document

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#614]
Attempted to create a new document and kept getting "please enter document title to create a document" error.  Couldn't successfully create a document.  Screen shot of where I ended up...

<img width="1412" alt="screen shot 2015-09-09 at 6 57 49 am" src="https://cloud.githubusercontent.com/assets/2349231/9760107/3e738372-56c0-11e5-8b77-559cd6554662.png">

**Comment by krues8dr** [comment]
Fixed in `dev`.
