### ISSUE TITLE
User Account Verification Page Does Not Exist

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#616]
Clicked on verification email to verify @nickom, but got the below page instead of the admin page: 

<img width="1411" alt="screen shot 2015-09-09 at 1 10 41 pm" src="https://cloud.githubusercontent.com/assets/2349231/9768828/4335268e-56f4-11e5-9cd9-7b8eed005b5b.png">

**Comment by boboroshi** [comment]
Tangentially, "You are lost." is not a very friendly message for a 404. It implies the user screwed up.

**Comment by krues8dr** [comment]
What if I add `exits are SOUTH, NORTH, and /` ?

**Comment by boboroshi** [comment]
lol. While I like the reference, do you feel most Madison users will understand it? 


![](http://i.ytimg.com/vi/dlbhipB2PcU/hqdefault.jpg)


This might capture it better, but again, you're dealing with the full gamut of internet users here. What some find playful others would find confusing or worse.

**Comment by cmbirk** [comment]
We have some "Frowning Father" images we can plug in here.

**Comment by krues8dr** [comment]
@seamuskraft can you please forward me the email in question?  Thanks!

**Comment by krues8dr** [comment]
Fixed the original issue, opened #619 for the 404 page.
