### ISSUE TITLE
Table on Contents sidebar sometimes overlaps with text

### ISSUE THREAD

**Issue by nickom** [opengovfoundation/madison#617]
Only happens with certain browser window widths, but the minimum buffer should be increased a bit so this doesn't happen:
<img width="728" alt="screen shot 2015-09-11 at 12 22 53 pm" src="https://cloud.githubusercontent.com/assets/3171982/9820327/2be8913a-5881-11e5-94b3-34ec4f1dac9e.png">

**Comment by sethetter** [comment]
New UI in v4!
