### ISSUE TITLE
Make 404 page better.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#619]
Needs work, per #616

**Comment by ritvikgautam** [comment]
I'll do this.

**Comment by krues8dr** [comment]
Thanks @ritvikgautam - but I'm not sure that makes it any more clear.  For most of our users, a 404 error is pretty opaque.  I think we need some more wording here, along the lines of `The page you're looking for is no longer here.  It may have moved, or the document may have been taken down by the author.`  

Even better would be to have below that suggested links - go to the home page to search for documents, and maybe a custom link to a google search for whatever they had originally requested in the url.

**Comment by ritvikgautam** [comment]
Sure! I'll look into that.

**Comment by ritvikgautam** [comment]
I've made some changes. Please check now. 
I've added the text as per your suggestion and have included a link to read more about the error on wiki.

**Comment by krues8dr** [comment]
That's great @ritvikgautam - this is definitely better than the old one we had!  Thanks!
