### ISSUE TITLE
Green banner font?

### ISSUE THREAD

**Issue by nickom** [opengovfoundation/madison#620]
@krues8dr tells me the right font is not loading (seen in Chrome and Safari):
<img width="1311" alt="screen shot 2015-09-14 at 10 46 27 am" src="https://cloud.githubusercontent.com/assets/3171982/9852739/e103cfa0-5acd-11e5-8de5-6a0de94d66c5.png">

**Comment by krues8dr** [comment]
Looks like none of the google fonts are loading, I must have messed up something.  I can also see that font awesome *is* loading but not showing up for everyone else.  Something strange is afoot.

**Comment by krues8dr** [comment]
@nickom Is this now resolved?
