### ISSUE TITLE
Grunt not always generating new files

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#627]
Might be a race condition?

**Comment by cmbirk** [comment]
Yeah, I think that's likely the case.  I have a different build process set up for a different project that I'll take a look at real quick.  It's in gulp, but uses similar packages so I'll see if it translates

**Comment by krues8dr** [comment]
It seems to work fine on the Editor so far too.

**Comment by cmbirk** [comment]
Well, it looks like gulp is much better suited to handle task chain dependencies.

**Comment by krues8dr** [comment]
I don't think we need to redo our entire tooling for a single error.

**Comment by cmbirk** [comment]
No, there are ways to do the same thing in grunt, it's just not as clean.  May want to visit that down the road

**Comment by krues8dr** [comment]
Well if it's cleanliness we're after, why not `make`?  :trollface:

**Comment by cmbirk** [comment]
Aw, hell.  Let's just go back to flat HTML then... ;)

**Comment by krues8dr** [comment]
:shipit:

**Comment by krues8dr** [comment]
+`priority` 'cause this is really starting to tick me off. Ugh.

**Comment by krues8dr** [comment]
Superseded by #919
