### ISSUE TITLE
Adding annotations doesn't update side numbers.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#628]
Need to trigger the binding to update those.  Easy fix is just to refresh that data on update.

**Comment by cmbirk** [comment]
It's running into a `[ngRepeat:dupes]` error.  The fix is something like `ng-repeat="something in somethingElse as $index` I think.

**Comment by cmbirk** [comment]
or rather `track by $index`

http://www.anujgakhar.com/2013/06/15/duplicates-in-a-repeater-are-not-allowed-in-angularjs/

**Comment by krues8dr** [comment]
I think whatever is happening here is also causing DCgov/dc-madison#60

**Comment by sethetter** [comment]
New UI in v4!
