### ISSUE TITLE
Remove dislike button

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#633]
per conversation this morning, doesn't actually help to remove noise, ends up removing valuable content.

**Comment by cmbirk** [comment]
Yeah.  Talked about moving to a Product Hunt model.

**Comment by krues8dr** [comment]
I'm not for sale.  Wait, right, the website.

**Comment by cmbirk** [comment]
This mean changing the 'thumbs up' icon to an up arrow similar to Product Hunt's.  This changes the connotation away from 'liking', which can be subjective.

<img width="1394" alt="screen shot 2015-11-12 at 1 06 06 pm" src="https://cloud.githubusercontent.com/assets/764851/11128250/4ab8d9e2-893e-11e5-89cb-078f4db4d962.png">

**Comment by cmbirk** [comment]
This also means we will need to change the way that the items are sorted on the right hand side.

**Comment by sethetter** [comment]
Removed it from the UI with 91dfb23, let me know if I missed any places.

I'm going to update the `activityOrder` functions next. I also plan to write a migration to clean out dislikes from the database unless there's any obligation. Only reason I could see is if we change our minds on this and want the previous dislikes back again (assuming this is a no).

**Comment by krues8dr** [comment]
:+1:

**Comment by sethetter** [comment]
@cmbirk @krues8dr Code check! -> 94de708

**Comment by krues8dr** [comment]
@cmbirk I think one thing we might want to do here is order the comments on the api-side in order of likes? This will make the pagination task ( #604 ) easier. That should happen in [the Comment model](https://github.com/opengovfoundation/madison/blob/94de7089ff95ede9cc7c03f3cfa733140c8d3acf/app/models/Comment.php#L158) I think.

**Comment by sethetter** [comment]
@krues8dr There were a couple places in angular controllers that took dislikes into account for activityOrder as well. I'll take a look at ordering comments from API by likes for this now.

**Comment by cmbirk** [comment]
Yeah, we'll only want to do the comments here, because the annotations are line-based ( and then sorted by grouping ).

**Comment by krues8dr** [comment]
:+1:

**Comment by sethetter** [comment]
Done in f8b51ab, @krues8dr, @cmbirk - code check? I think I could have done this with a SQL query for a little better performance, but it would have been a hell of a query.

**Comment by krues8dr** [comment]
You'll have to do this with a query for the pagination that's to come.  We can punt on this for now, and create a "total" column in the docs table when we do that.

**Comment by sethetter** [comment]
Cool, I assume you mean on the comments table, but I follow. Sounds good!
