### ISSUE TITLE
Floating/Out of Place "Read More" Button on the Home Page

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#634]
I'm using Chrome Version 45.0.2454.93 (64-bit).

<img width="1203" alt="screen shot 2015-09-18 at 10 20 44 am copy" src="https://cloud.githubusercontent.com/assets/2349231/9963340/d405d734-5df8-11e5-8cff-306c024ae979.png">

**Comment by krues8dr** [comment]
There's no summary so it's stuck in the wrong place. :/

**Comment by seamuskraft** [comment]
Roger that.  But I don't think we should force a summary to be posted on
docs (in order to not screw up the formatting).  Right?

- Seamus

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation <http://OpenGovFoundation.org>
Ph: +1-760-659-0631
Tweet Us @FoundOpenGov <http://twitter.com/foundopengov>

**Comment by cmbirk** [comment]
Yeah, we shouldn't force summaries.  That should be a block element instead of floating.  It appears to only happen on one viewport size.

**Comment by cmbirk** [comment]
@krues8dr this is resolved, correct?

**Comment by cmbirk** [comment]
It is.

**Comment by krues8dr** [comment]
I don't think it was...?

**Comment by cmbirk** [comment]
oh, nope you're right.  It only happens on a mid-size window.

**Comment by sethetter** [comment]
New UI in v4!
