### ISSUE TITLE
Add TOS etc to templates

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#636]
Looks like that got skipped in the design.

**Comment by krues8dr** [comment]
These documents should be added to start: https://github.com/opengovfoundation/site-policy/tree/master/markdown

**Comment by sethetter** [comment]
Done in 1a4867

**Comment by krues8dr** [comment]
One small tweak here - `pull-right` isn't a semantic class name (if we want to put it on the left it no longer makes sense), so please replace that class with something more semantic - `footer-links` or something.  (Of course in the sass you can just make `.footer-links { @extend .pull-right; }`.

**Comment by sethetter** [comment]
@krues8dr you can tell I've been living in the backend world for a little too long :)

Fixed in 2e2be3c and c46f971.

**Comment by krues8dr** [comment]
:+1: :shipit:
