### ISSUE TITLE
Facebook sign up: "Undefined index: first_name" error

### ISSUE THREAD

**Issue by Vanuan** [opengovfoundation/madison#637]
I set up a new facebook app. API version is "2.4".
I set up client_id and secret.
When I try to signup I get  "Undefined index: first_name" error.

**Comment by Vanuan** [comment]
Error output:
```
open: /app/app/controllers/UserController.php
            $token = $fb->requestAccessToken($code);
 
            // Send a request with it
            $result = json_decode($fb->request('/me'), true);
 
            // Remap the $result to something that matches our schema.
            $user_info = array(
                'fname' => $result['first_name'],
                'lname' => $result['last_name'],
                'email' => $result['email'],
```

**Comment by Vanuan** [comment]
Graph API's "/me" now returns this:

```
{
  "name": "First Last",
  "id": "12345678990"
}
```

No email, first name or last name returned

**Comment by krues8dr** [comment]
I wouldn't be at all surprised if facebook changed their API format without letting anyone know.  Thanks for the report!

**Comment by Vanuan** [comment]
To fix this, one should use this:

    /me?fields=first_name,last_name,email,id

**Comment by krues8dr** [comment]
Nice work, thanks!

**Comment by hammadkhan** [comment]
Thanks it helped!
