### ISSUE TITLE
Request to be a sponsor link leads to 404

### ISSUE THREAD

**Issue by Vanuan** [opengovfoundation/madison#638]
Navigating to `/documents/sponsor/request` (from account settings page) redirects to 404.

**Comment by krues8dr** [comment]
Yup, looks like this didn't make it through the conversion from laravel -> angular.  I'll hack this together real quick.

**Comment by cmbirk** [comment]
@krues8dr was this done?

**Comment by krues8dr** [comment]
Yeah, it's done on `dev` branch.
