### ISSUE TITLE
Admin set up doesn't work

### ISSUE THREAD

**Issue by Vanuan** [opengovfoundation/madison#641]
Step to reproduce:

1. artisan db:clear
2. artisan migrate
3. set ADMIN_EMAIL/PASS environment variable
4. artisan db:seed
5. Try to login using values from env

Expected:

successful login

Actual:

Email does not exist!

**Comment by Vanuan** [comment]
Database seeder has this:

        if (app('env') == 'production') {
            return;
        }


How am I supposed to create admin user?

**Comment by werdnanoslen** [comment]
I also have this issue. After also creating the user via the "sign up" feature, I was able to log in, however there is no change in anything, e.g. no ability to add documents.

**Comment by krues8dr** [comment]
Right, users have to be confirmed to add documents - for our use case, we don't want just anyone drafting legislation on an official government website.  And, of course, the only way through the website to approve users is to be an admin yourself.  You can, however, just go into the database and promote yourself.  

I'll work on a fix for the original issue this week.

**Comment by krues8dr** [comment]
Ok, db:seed is part of laravel, so we don't have any control over that and can't fix.

So your options here instead are:

1) Run in development mode, create your user, and then switch to production mode

or

2) Use the `user:create` and `user:addRole` commands to create a new user and promote them to `Admin`.

**Comment by Vanuan** [comment]
db:seed is part of laravel, so we don't have any control over that and can't fix.

WHAT?

**Comment by krues8dr** [comment]
Oh wait.  I see it now, we're using ours, not laravel's.

**Comment by Vanuan** [comment]
Look here:

https://github.com/opengovfoundation/madison/blob/070850ece6b68043fc878676643688429517b353/app/database/seeds/DatabaseSeeder.php#L48

**Comment by krues8dr** [comment]
Yup, will resolve tomorrow.  Bumped and prioritized.

**Comment by krues8dr** [comment]
Sorry for the confusion.

**Comment by krues8dr** [comment]
Fixed, LMK if that doesn't work!  Thanks again for the report!
