### ISSUE TITLE
XMLHttpRequest: http vs https

### ISSUE THREAD

**Issue by Vanuan** [opengovfoundation/madison#642]
Error:

```
'https://.../administrative-dashboard/site-settings' was loaded over HTTPS,
but requested an insecure XMLHttpRequest endpoint 'http://.../api/docs?title=%D0%BF%D0%BE%D0%B4%D0%B0'
```

**Comment by krues8dr** [comment]
I assume this is from typing in the entry box on the Site Settings page to choose a new featured document?  Hmm, I'm not seeing this one on the live site, it's all serving properly over https.

```
XHR finished loading: GET "https://mymadison.io/api/docs/?title=tes".
XHR finished loading: GET "https://mymadison.io/api/docs/?title=test".
```

**Comment by Vanuan** [comment]
@krues8dr This is in master. Mymadion.io is not master, I believe?

**Comment by krues8dr** [comment]
It is using master on the live site, though it might be a commit or two behind at any given time.  Can you check to see if it's following a redirect or anything to get there?  That's really odd.

**Comment by sethetter** [comment]
Should be good to go in v4 now.
