### ISSUE TITLE
Locked composer package versions don't jive with common RHEL repos

### ISSUE THREAD

**Issue by werdnanoslen** [opengovfoundation/madison#645]
I've been trying to set up Madison on RHEL, but the versions specified in the composer.lock file don't work well with commonly trusted RHEL repos. Would you consider revising package version requirements so that operators on large systems (like universities and, probably, government offices) can use php versions tracked by trusted repos? For example, many important packages tracked by those repos still specify v5.4

**Comment by krues8dr** [comment]
We haven't looked this over in a while, to be perfectly honest - if you can list particular packages that are problematic, we're happy to revise and update.  

That being said, we're not going to officially support PHP 5.4 moving forward since it's [EOL and not receiving security patches](http://php.net/supported-versions.php).  PHP 5.5 will get the same treatment next year.  CentOS is my preferred flavor, so I'm sympathetic to the older requirements of RHEL, but this is in line with the strong recommendations of the core PHP developers.  

Of course, if you prefer not to trust third party repos, you can always build from source.

**Comment by krues8dr** [comment]
(Also, there's [RHEL Software Collections](http://developerblog.redhat.com/2013/01/28/software-collections-on-red-hat-enterprise-linux/),  [PHP 5.6](https://www.softwarecollections.org/en/scls/rhscl/rh-php56/).)

**Comment by werdnanoslen** [comment]
Yep, I went ahead and started configuring everything on 5.6, but things like composer and phpmyadmin in common repos still require 5.4. So I'm spending time building/maintaiing these things manually

**Comment by krues8dr** [comment]
That is a pain, and I agree it's less than ideal.  We're looking into config management/containerization to help alleviate some of these pains right now.  Suggestions and input are welcome!

**Comment by werdnanoslen** [comment]
All required packages for RHEL can be found in Remi repos

**Comment by krues8dr** [comment]
:+1:

**Comment by krues8dr** [comment]
@werdnanoslen would you mind copying and pasting the details of what you had to run here so I can add a new section to the installation instructions, please?  Thanks!

**Comment by werdnanoslen** [comment]
I'm running Red Hat Enterprise Linux Server release 7.1 (Maipo), using these packages:
```
php.x86_64                        5.6.14-1.el7.remi        @remi-php56
php-bcmath.x86_64                 5.6.14-1.el7.remi        @remi-php56
php-cli.x86_64                    5.6.14-1.el7.remi        @remi-php56
php-common.x86_64                 5.6.14-1.el7.remi        @remi-php56
php-gd.x86_64                     5.6.14-1.el7.remi        @remi-php56
php-gmp.x86_64                    5.6.14-1.el7.remi        @remi-php56
php-mbstring.x86_64               5.6.14-1.el7.remi        @remi-php56
php-mcrypt.x86_64                 5.6.14-1.el7.remi        @remi-php56
php-mysqlnd.x86_64                5.6.14-1.el7.remi        @remi-php56
php-pdo.x86_64                    5.6.14-1.el7.remi        @remi-php56
php-pecl-jsonc.x86_64             1.3.9-1.el7.remi.5.6     @remi-php56
php-pecl-yaml.x86_64              1.2.0-1.el7.remi.5.6     @remi-php56
php-pecl-zip.x86_64               1.13.1-1.el7.remi.5.6    @remi-php56
php-php-gettext.noarch            1.0.11-12.el7.remi       @remi
php-phpseclib.noarch              2.0.0-4.el7.remi         @remi
php-process.x86_64                5.6.14-1.el7.remi        @remi-php56
php-recode.x86_64                 5.6.14-1.el7.remi        @remi-php56
php-symfony-class-loader.noarch   2.7.5-1.el7.remi         @remi
php-symfony-common.noarch         2.7.5-1.el7.remi         @remi
php-symfony-yaml.noarch           2.7.5-1.el7.remi         @remi
php-tcpdf.noarch                  6.2.12-1.el7.remi        @remi
                                  6.2.12-1.el7.remi        @remi
php-tidy.x86_64                   5.6.14-1.el7.remi        @remi-php56
php-xml.x86_64                    5.6.14-1.el7.remi        @remi-php56
phpMyAdmin.noarch                 4.4.15-1.el7.remi        @remi
```
