### ISSUE TITLE
PDO exception on artisan migrate

### ISSUE THREAD

**Issue by werdnanoslen** [opengovfoundation/madison#646]
Following install.md on RHEL 7.1 using PHP 5.6.14 gives me the following error on the last step:
```
$ php artisan migrate
[PDOException]
SQLSTATE[HY000] [2002] No such file or directory
```

**Comment by cmbirk** [comment]
It looks like you may not have MySQL running.

**Comment by werdnanoslen** [comment]
No, it's definitely running

**Comment by cmbirk** [comment]
Make sure you're migrating in the right environment by using
`php artisan migrate --env=your_environment`

**Comment by krues8dr** [comment]
Yeah, this looks like a configuration issue.  That error means that PDO can't connect to MySQL with the supplied credentials.  Other obvious causes could be that the user can't connect via localhost (if that's how you have it setup).

**Comment by werdnanoslen** [comment]
The credentials I put in madison/app/config/creds.php are the same as the user that has access to the madison database. I have tried using both --env=production and development, as are specified in the files (I confess I'm not very familiar with this, so perhaps I'm missing something?).

**Comment by krues8dr** [comment]
Hmm.  I'm going to run through the really low level questions here, so apologies if these are obvious:

* In the application root (the level above `public/`) do you have a `.env.php` file that [looks like this](https://gist.github.com/krues8dr/79dfd358a15e8716e24c)?
* Have you tested logging in with the user info in that file through the mysql command line client?  (`mysql -u madison-user -p madison-database`)
* Can you set `debug => true` in your `config/app.php` and see if that gives any additional information, and has the correct user login info listed?  (I think it shows that still...)

**Comment by cmbirk** [comment]
You won't be able to pull up the site without running the migrations.  The credentials for the application are in the `.env.php` file mentioned above.  Try setting up that file and running the migrations again.

**Comment by werdnanoslen** [comment]
Ok, I've copied the credentials from creds.php in .env.php (I suggest this step go into install.md), that fixed the migration issues.

**Comment by cmbirk** [comment]
Awesome.  Thanks for the heads up @werdnanoslen .  We'll get that added.  Pull requests are also always welcome ;)

**Comment by werdnanoslen** [comment]
No problem: #648.
