### ISSUE TITLE
API calls 404 on fresh install

### ISSUE THREAD

**Issue by werdnanoslen** [opengovfoundation/madison#649]
I've followed install.md so far (also ran bower and npm installs), and everything seems configured properly, but when loading it the browser for the first time, the api 404's. I have my server's DocumentRoot set to the madison/public directory.

Open the web console here: [http://waltprogram.lmc.gatech.edu](http://waltprogram.lmc.gatech.edu)

**Comment by krues8dr** [comment]
It looks like *none* of your url rewriting is working.  Is this Apache?  If so, you need to make sure `AllowOverride All` is set for the VirtualHost.

**Comment by werdnanoslen** [comment]
Ah, thanks, I hadn't configured that when I changed the document root.

**Comment by krues8dr** [comment]
Great, looks like that cleared it up!  Nice!

**Comment by werdnanoslen** [comment]
Yep, added that and instructions to #648
