### ISSUE TITLE
Improve custom theming.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#650]
Two things to be done here:

* [x] Make most of our variable settings in `globals.scss` and elsewhere have the `!default` flag.
* [x] Create a `custom` folder and use glob-import to bring it in first. (`@import ./custom/*`), overriding any defaults.

**Comment by sethetter** [comment]
Do we want to allow them to override more than just variables?

**Comment by krues8dr** [comment]
That's the only thing that's critical right now, I think.  If you have other suggestions, let's hear em!  :)

**Comment by sethetter** [comment]
Well, if we import at the bottom then they can override whatever they want. I didn't know if we wanted to give them that much control though ;)

**Comment by sethetter** [comment]
Scratch that, variables have to be set ahead of time, just tested, haha. My mistake!

**Comment by sethetter** [comment]
@krues8dr You said add `!default` to "most" settings. Is there any I should avoid explicitly?

**Comment by krues8dr** [comment]
Not off the top of my head, I really just meant that we probably want to keep this to settings/globals/etc and not like every variable in the pages files etc.  There are a few tricky places in the bootstrap overrides that might fail miserably but otherwise I'd say just have at it.

**Comment by sethetter** [comment]
:+1:

**Comment by sethetter** [comment]
@krues8dr @cmbirk code check? 556af39

**Comment by krues8dr** [comment]
This looks good.  :+1: :shipit:

**Comment by barryvdh** [comment]
Do you have any suggestions for changing the views? I'd like to keep my fork a bit up-to-date but we require some front-end changes in the templates, which make it hard to avoid conflicts.

**Comment by krues8dr** [comment]
@barryvdh Can you let us know exactly what you're changing? (Links to examples are great.) Ideally I'd like everything to be completely styleable, but radical changes from the existing structure are going to be hard.

**Comment by krues8dr** [comment]
For what it's worth, there will likely be one other major refactoring in the near future on the theme front to deal with lots of outstanding mobile issues.

**Comment by barryvdh** [comment]
The fork is here: https://github.com/Socioneers/pvda-madison
Most changes are: 
- different styling (styling would be fixed with this issue)
- Different logo, welcome text etc (changes in partials)
- Extra pages (manual etc), changes in menu (Could be in the database as html/markdown?)
- Translation (is since fixed with internationalisation, but has to be backported still). Not always direct translation, sometimes slightly different meanings.
- Disabling annotations and sidebar, only allow discussion.
- Different permissions (only registered users can see documents and the dashboard)
- Some moving around of the activity feed/ document list.
- Restoring of category filter, for just categories (not sponsors)
- Removal of certain features, like dislike/flagging and 'against'  flag, adding 'support' to stats.
etc.

And some things for the feature request list;
 - moderating discussions, comments etc for admins.
 - improving mobile layout (but should be fixed in your refactoring)
 - Some minor features, like linkifying links, counting words, adding validation rules, extended document filtering (on author/comments) etc

**Comment by krues8dr** [comment]
Ok let me run down these real quick:

> different styling (styling would be fixed with this issue)
:white_check_mark: 

> Different logo, welcome text etc (changes in partials) 
Is there anything here not covered by this and #513 ? 

> Extra pages (manual etc), changes in menu (Could be in the database as html/markdown?)
Interesting.  We're definitely edging closer to this with [how I've redone the routes for content pages](https://github.com/opengovfoundation/madison/commit/fa85aed955cc3886e4e7c1d41c03de179b1e1c78#diff-864393ed8ecec6d1624139179851e608R236). But I'm not sure how to do this in the database and still maintain internationalization, since we'd have lots of duplicates.  Maybe each page is keyed by both language *and* slug?  We'd have to think through how this would impact Angular's ability to switch languages as well.  But I'm 100% ok with content being stored in the database and delivered via API, just to clarify.  On the other hand, we're halfway to being Wordpress in that case...

> Translation (is since fixed with internationalisation, but has to be backported still). 
:white_check_mark: 

> Not always direct translation, sometimes slightly different meanings.
Right.  Is there anything missing here that you're aware of?

> Disabling annotations and sidebar, only allow discussion.
That's definitely reasonable - if you want to do this as a setting and submit a pull request we'd accept that.

> Different permissions (only registered users can see documents and the dashboard)
We *do* need a more granular permission model, I assume there's quite a bit of backend work here though to prevent users from just querying via the API to get data.  If you have suggestions here we're open to them!

> Some moving around of the activity feed/ document list.
You mean the actual blocks as they appear on the homepage and document page?  Can you tell me what you need that you can't do with CSS?

> Restoring of category filter, for just categories (not sponsors)
Yeah, the category filter is broken a bit.  Do you mean you want to disable sponsor search also?

>Removal of certain features, like dislike/flagging and 'against' flag, adding 'support' to stats. etc.
We just removed dislike permanently, but content flagging is pretty important for most instances to avoid spam, etc.  Are you for not allowing users to report inappropriate content?  

And for the second part of that, you're getting rid of "Oppose" altogether?  That might be easiest with CSS, really (like how reddit does it).


> moderating discussions, comments etc for admins.
For this, are you saying admins can remove comments, or admins have a custom style for replying to comments, or something else?

> improving mobile layout (but should be fixed in your refactoring)
Yup, this is a big one. Haven't had time to tackle it yet.

>linkifying links, counting words, adding validation rules, extended document filtering (on author/comments) etc
I think we'd be onboard for pull requests on any/all of these!

Thanks so much for taking the time to put all of that together.  I'll turn my comments above into actual Github issues first thing next week!

**Comment by barryvdh** [comment]
> For this, are you saying admins can remove comments, or admins have a custom style for replying to comments, or something else?
Removing comments (or perhaps modify to remove inappropriate content) or entire threads in a discussion. Right now you can flag a comment, but not remove it, right? Or am I overlooking something.

**Comment by barryvdh** [comment]
> Maybe each page is keyed by both language and slug? We'd have to think through how this would impact Angular's ability to switch languages as well. But I'm 100% ok with content being stored in the database and delivered via API, just to clarify. On the other hand, we're halfway to being Wordpress in that case...

I think it would be good, also to separate the concerns for the developers (maintaining madison) and the admins/users, managing the content. It doesn't have to be as complex as Wordpress, but a simple content management tool for pages and perhaps some other strings (banners, welcome text, footer etc) and make the menu editable, would be nice.
Perhaps there is some nice 3rd party extension we could use for this.

**Comment by krues8dr** [comment]
>Removing comments (or perhaps modify to remove inappropriate content) or entire threads in a discussion. Right now you can flag a comment, but not remove it, right? Or am I overlooking something?

No, that's correct.  I think flagging was intended to send an email to the admins for review and to let them remove/hide comments, but I don't think this was ever built out.  @cmbirk ?

> I think it would be good, also to separate the concerns for the developers (maintaining madison) and the admins/users, managing the content. It doesn't have to be as complex as Wordpress, but a simple content management tool for pages and perhaps some other strings (banners, welcome text, footer etc) and make the menu editable, would be nice.
Perhaps there is some nice 3rd party extension we could use for this.

That's a good idea.  I'll add an issue to investigate this.
