### ISSUE TITLE
If there are no documents, make sure that Featured and Active document areas don't show up.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#651]
On http://waltprogram.lmc.gatech.edu/ right now, they have no documents and just have big blank areas on the page.  That's less than ideal, we need some sort of default content here.

**Comment by werdnanoslen** [comment]
For reference, since the site's under development: [http://imgur.com/Wi5DDTE](http://imgur.com/Wi5DDTE)

**Comment by cmbirk** [comment]
Right now we have the `php artisan db:seed` set up to enter a couple default documents.  We can certainly also add placeholders there.

**Comment by sethetter** [comment]
Handled in v4
