### ISSUE TITLE
Annotations + Comments Showing Up Out of Place and One Doc Behind

### ISSUE THREAD

**Issue by kylebarney** [opengovfoundation/madison#654]
Viewed in Chrome browser on a Mac OS.

Floating annotation and discussion icons floating at the top of the page (see screenshot).

The icons also do not pertain to the document being view but rather the document the used viewed *previous* to the current document. (Notice how on the screenshot the sidebar is open, but refers to a letter from the IRS rather than the document on the screen.)

![madison_bug_10-29-15](https://cloud.githubusercontent.com/assets/15039520/10841242/34163310-7ead-11e5-9ab6-170adaa20c29.png)

**Comment by kylebarney** [comment]
Just saw that this is a duplicate of #573.

**Comment by krues8dr** [comment]
@kylebarney Can you reproduce this consistently? Every time, or just some of the time? If so, what OS and browser are you using?  Thanks!

**Comment by kylebarney** [comment]
I'm able to reproduce the bug consistently on OS X 10.11.1 with both the Chrome (46.0.2490.80 (64-bit)) and Firefox (41.0.2) browsers. The bug also appear when accessing the site on Windows 8.1 with Chrome (46.0.2490.80 m) and Firefox (41.0.2).

The bug did **not** appear when accessing the site on Windows 8.1 with IE (11.0.9600.18053).

In all cases, the bug does not appear on the first document selected, but after 1) returning to the homepage and 2) selecting another piece of legislation, the bug appears. As noted before, the annotation being displayed through the bug is an annotation for the previous document viewed rather than the current document on the user's screen. (Oddly enough, it seems to consistently display the second (from top to bottom) annotation from the previous document.) In one instance, the bug appeared briefly and then disappeared, but other than that the appearances have been consistent.

**Comment by kylebarney** [comment]
After further investigation, it appears that there are a lot of additional annotations stacked up behind that front bug - see screenshot. (Hover your cursor over the right hand side of the bug to replicate.)

![screen shot 2015-10-30 at 11 38 49 am](https://cloud.githubusercontent.com/assets/15039520/10853305/01563ad0-7efb-11e5-8c68-3bc64d2e6b43.png)

Additionally, (and this is really weird), if I right-click on an item within the top grey header (not just the background, but an actual link), the bug disappears. This only works when you click on an item in the grey header - nowhere else on the screen. But... this only works on a viewport that takes up all or most of the screen - not on more narrow views. (This was on Chrome with OS X.)

**Comment by krues8dr** [comment]
I suspect that the old annotations aren't being removed properly when the view is changed.  I'm not sure why that is, they should be destroyed when they leave scope.  It could be that the magic I'm doing to parse them at the model layer is putting them into global scope; it could be as simple as a missing `var` declaration.

**Comment by cmbirk** [comment]
There may be an angular `$scope` issue.  That's designed to handle this.

**Comment by cmbirk** [comment]
I'm having trouble reproducing the "one document behind" issue.  Annotator gets destroyed and the annotations get cleared on every `$stateChangeStart` in app.js.

Annotator is then reloaded and the annotations reloaded on instantiating the `DocumentPageController`.  

This should handle annotations persisting between documents.  I'm taking a look at the comments now.

**Comment by cmbirk** [comment]
I am now able to reproduce the annotation error.  Looking through it

**Comment by cmbirk** [comment]
Aha!  I think the `annotations` property is being cleared in the `annotationService` but not the `annotationGroups` property.

That's why annotations were showing up as detached annotations - the new document didn't contain their parent nodes.  This was being undiagnosed when we simply hid detached annotations.

**Comment by cmbirk** [comment]
This was fixed in the above PR (#779)
