### ISSUE TITLE
Not receiving confirmation email, permissions error

### ISSUE THREAD

**Issue by werdnanoslen** [opengovfoundation/madison#657]
I'm able to create a user in the database via sign up page and then log in, but I never get a confirmation email and nothing requiring authentication works.

I'm getting this error upon clicking the "Sign Up" button on the registration page (POST to http://waltprogram.lmc.gatech.edu/api/user/signup):
```
Error in exception handler: The stream or file "/var/www/html/madison/app/storage/logs/log-apache2handler-2015-11-12.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/madison/bootstrap/compiled.php:8424
```

Apache write permissions set on app/storage:
```
drwxrwxr-x. 10 apache apache 4096 Nov 12 14:38 .
drwxr-xr-x. 15 apache apache 4096 Nov 12 14:38 ..
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 cache
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 db_backups
drwxrwxr-x.  6 apache apache   63 Nov 12 14:38 docs
-rwxrwxr-x.  1 apache apache   17 Nov 12 14:38 .gitignore
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 import_logs
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 logs
drwxrwxr-x.  2 apache apache   43 Nov 12 14:48 meta
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 sessions
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 views
```

Is there another user/group that needs access to the storage?

This is a fresh install, after going through the installation guide exactly, and everything worked fine. This is running on Red Hat Enterprise Linux Server release 7.1 (Maipo) at [http://waltprogram.lmc.gatech.edu/](http://waltprogram.lmc.gatech.edu/)

**Comment by cmbirk** [comment]
Those look right to me at first glance.  Can you confirm the same permissions on the sub-folders?  @krues8dr you see anything I'm missing?

**Comment by krues8dr** [comment]
We need to see the permissions in the logs directory to be sure, but I'd guess that the file in question isn't writable by `apache` according to that error.  You could try `sudo chown -R apache:apache "/var/www/html/madison/app/storage/` to be safe.

If you're not getting a confirmation message, then it might not be sent.  If you're using the builtin mailer, you'll have to check (I think) `/var/log/maillog` to see if the message was sent - of if you're using sendgrid or a similar service, check the logs on their side.  It's possible there's an issue with mailsending not using a service.

**Comment by werdnanoslen** [comment]
The ```app/storage/logs``` folder mentioned in the error:
```
drwxrwxr-x.  2 apache apache   23 Nov 12 14:38 .
drwxrwxr-x. 10 apache apache 4096 Nov 12 14:38 ..
-rwxrwxr-x.  1 apache apache   13 Nov 12 14:38 .gitignore
```

Also, I'm checked out on the last release: 1.8.5

**Comment by krues8dr** [comment]
Is `Apache` running as the `apache` user?  That's really the only other thing I can think of here.

**Comment by werdnanoslen** [comment]
Ran the usual suspects ```ps aux | egrep '(apache|httpd|www-data)'``` and yes, it's ```apache```

**Comment by krues8dr** [comment]
Hmm.  Extended permissions maybe?  Can you run [`getfacl`](http://www.lpice.eu/cz/domu/linux-tip-of-the-month/05-2013/) on it?

**Comment by werdnanoslen** [comment]
Nothing out of the ordinary
```
# file: app/storage/
# owner: apache
# group: apache
user::rwx
group::rwx
other::r-x
```
```
# file: app/storage/logs/
# owner: apache
# group: apache
user::rwx
group::rwx
other::r-x
```

**Comment by krues8dr** [comment]
Sorry, but that's the last thing I can think of, I can't think of a single other thing that can cause it to throw a permissions error.  You might need to turn on debug in the app config to get more details here, but even with it really there's nothing else that could be happening that I can come up with.

**Comment by krues8dr** [comment]
You might `touch` that file with and chown it to apache to see if that fixes it magically?

**Comment by werdnanoslen** [comment]
Tried that, too, but it can't open the file. I did turn on debug, but no error messages were available.
Thanks for helping out!

**Comment by krues8dr** [comment]
Oh!  Wait, that `.` at the end is indicating a SELinux flag.  Try `ls -Z` on the directory, and `getenforce` will tell you what mode SELinux is currently running at.

**Comment by werdnanoslen** [comment]
Oh wow nice catch, I didn't realize my sysadmin had set up SELinux on here! So many problems solved...

**Comment by werdnanoslen** [comment]
Yep, it was all SELinux's fault. So I set the proper attributes on the directory and it all works fine now. Also, the gmail problem was that gmail now requires you to explicitly allow low-security apps to access accounts. Thanks a ton for that attention to detail @krues8dr! Closing.
