### ISSUE TITLE
Reply on yourself doesn't refresh

### ISSUE THREAD

**Issue by barryvdh** [opengovfoundation/madison#671]
When replying on yourself a thread that you started yourself, the comment doesn't seem to appear. On other cases it does appear.
I'm not getting an error, just nothing happens. On manual refresh, the comment is there.

**Comment by krues8dr** [comment]
I strongly suspect this is related to #628

**Comment by barryvdh** [comment]
> TypeError: undefined is not an object (evaluating 'activity.comments.push')

```
if (activity.comments) {
     activity.comments.push(data);
 }```
Works in the succeshandler after a comment, but not sure why it would be undefined.

**Comment by barryvdh** [comment]
Sorry that doesn't fix it, still not working. Hope that error helps you at least something.

**Comment by sethetter** [comment]
Should be good in v4
