### ISSUE TITLE
Manage categories (no auto-tagging)

### ISSUE THREAD

**Issue by barryvdh** [opengovfoundation/madison#672]
Is is possible to disable the auto-tagging of categories and manage them in the admin? Or should I just create them 1 time and then disable it in the API?

**Comment by sethetter** [comment]
Ran into this today as well. It seems a little too easy to be typing and accidentally create a junk category. Might create quite a bit of DB clutter.

**Comment by sethetter** [comment]
No more categories in v4, closing until that changes!
