### ISSUE TITLE
Move file uploads to subfolder

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#673]
We'll want some sort of an `uploads` folder for our featured images (and anything else) so that we can easily symlink that for deployment.

**Comment by cmbirk** [comment]
Yeah, we'll just want to store this in the laravel `app/storage` directory that gets shared across deployments and then symlink a folder from the `public/img` directory

**Comment by cmbirk** [comment]
I actually think we're going to want to ultimately use the [Storage facade](http://laravel.com/docs/5.0/filesystem) for this.  May wait until ( and prioritize) the upgrade to Laravel 5.
