### ISSUE TITLE
Create system for allowing custom content pages

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#679]
I've [refactored the frontend routing to make it easier to have custom content pages](https://github.com/opengovfoundation/madison/commit/fa85aed955cc3886e4e7c1d41c03de179b1e1c78#diff-864393ed8ecec6d1624139179851e608R236), but we need an easier system here.  These all need to be resolved:

* Site admins should be able create their own content pages.
* Currently, content is stored in the localization files, but that isn't flexible.
* This still needs to support multiple locales.
* All routes are currently hardcoded in the routes file.

Potentially, we could store the content in the database and have multiple language versions as separate records.  The API could feed this list of pages to the app on load.  Alternatively, we could just have a folder of additional pages, broken into localized folders, that's `.gitkeep`ed in place, and gets loaded dynamically on load.  That's a bit cleaner because it keeps the frontend/localizations together in one place.

As discussed in #650.

**Comment by cmbirk** [comment]
+1.  I would think there's already a CMS-lite-like plugin for Angular that we could use.

**Comment by sethetter** [comment]
The file-based approach to this issue seems easier to get up and running quickly, but the idea of having an admin interface for managing custom pages seems like the long term ideal here (as long as it still supports multiple languages).

For the scope of this issue, I'm thinking we tackle it with a file-based approach first, and then have a separate issue for moving to an admin interface for custom content pages in the future.

@krues8dr thoughts?

**Comment by krues8dr** [comment]
I don't see any value in having extra files hanging out when we've got a perfectly workable database sitting there. ;)   Really, for the scope of this, it should just be copy-and-pasting the existing document edit code more or less - we've got an editor, management, etc all right there.  I'd just skip the locale bit for now, since most sites only are supporting one language at the moment anyway.

**Comment by sethetter** [comment]
@krues8dr just approaching the conversation from your initial thoughts up above :) Either way is good with me. I'll run with this.

**Comment by sethetter** [comment]
@krues8dr I'm thinking we want to move the "About" and "FAQ" pages into being managed by this feature as well, correct?

**Comment by krues8dr** [comment]
Yes please.  TOS, privacy policy, etc as well.

**Comment by krues8dr** [comment]
Minor complication: the current home page content will need to be edited as well.
