### ISSUE TITLE
Make annotations and discussion optional

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#680]
These should each be configuration flags.  There may also be cases where we want to override this in either direction on a per-document basis.  In general, Madison was create to allow users to discuss legislation, but there may be cases where the way we're using it is not relevant to some users.  Some agencies may also just wish to use it to publish documents.  Per the discussion on #650.

**Comment by sethetter** [comment]
@krues8dr Is this covered in #874? Or are we wanting something more with this issue?

**Comment by krues8dr** [comment]
Looks good.
