### ISSUE TITLE
Create a migration snapshot

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#686]
With the upgrade to Laravel 5.1 from 4.2 I would like to create a database snapshot and create a clean migration chain.  That way anyone creating a fresh madison instance won't have to deal with the cruft of the last series of migrations.  I'm worried that this will negatively impact current Madison users, however.

I'm wondering if moving the current set of migrations to `database/migrations/archive/4.2` or something like that would solve that issue.  That leaves the migrations in there in case someone needs them, but would let us clean up the `database/migrations` directory.

Would love to get some feedback from the community before making a decision on this.

@krues8dr @sethetter

**Comment by sethetter** [comment]
I think that makes sense. They could just be moved back into the migration folder for when an upgrade is going to be performed. We would just need to make sure that is clear for anyone performing the upgrade.

It's starting to sound like this might be a new version stamp for Madison as well, then we could include an upgrade guide that outlines these steps. Thoughts?

The only other thing I can think of is the `migrations` table and if it might need to be cleaned out too when clearing out the `migrations` folder.

**Comment by sethetter** [comment]
Moving away from multi-instance model, this doesn't seem as pertinent. Closing!
