### ISSUE TITLE
Error on create document 

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#690]
Getting the error “You must enter a document title to create a new document” and redirects to `/dashboard/docs` with a blank page.  I *think* this is fixed in `dev` somewhere, but double check.

**Comment by krues8dr** [comment]
So this *was* fixed waaaay back in 71ff5a6fac21c23cb1c7a0f29c94fbcfc6af3a29  but I didn't realize at the time this occurs in *two* places because our code is duplicated for both of the document pages.  Less than ideal.  We should DRY this up sometime.

**Comment by cmbirk** [comment]
Still getting this issue from the admin `Edit Documents` page

**Comment by cmbirk** [comment]
This was a cache issue.  Closing.

**Comment by krues8dr** [comment]
:+1:
