### ISSUE TITLE
Unable to create new document

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#702]
```
 Cannot create a new document any more.  Get the error “There was an error submitting the document. Please try again later.”.
```

**Comment by cmbirk** [comment]
Well, I'm getting another `502 Bad Gateway` error here... :rage:

**Comment by krues8dr** [comment]
Lovely.  :/  I'd check first for anything that touches Entrust.

**Comment by cmbirk** [comment]
This is resolved after installing on a clean non-forge server.  The proposed Ansible setup ( coming soon ) should solve this problem.
