### ISSUE TITLE
Scroll to annotation after logging in

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#713]
Clicking 'reply' on an annotation in the sidebar prompts the login modal.  After logging in I'm left at the top of the page.  It should scroll down and open the annotation I was trying to reply to.

**Comment by krues8dr** [comment]
Hmm.  Sounds like a bug; after submitting the modal, the screen shouldn't move at all, so scrolling back down shouldn't even be necessary.

**Comment by cmbirk** [comment]
The modal refreshed the page, which lost the position

**Comment by krues8dr** [comment]
This is also broken on the Discussion tab "login to comment" link, which actually loads the login page on click.

**Comment by sethetter** [comment]
Should be fixed with new v4 UI
