### ISSUE TITLE
Verifying independent sponsor refreshes page and disappears

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#722]
This should really be like the other verifications where we can see who's verified and who isn't with the radio set on the correct status.

Right now it's refreshing the page and losing the item.

**Comment by krues8dr** [comment]
This unfortunately doesn't work like the others, once you're denied, you are basically back to pre-pending.  We need a better way than a binary bit to handle this "properly".

**Comment by cmbirk** [comment]
There can be a 'pending', 'approved', and 'rejected' set of buttons, with the rejected button removing the request and sending the user back to 'pre-pending'.  The other statuses should be shown, though, with the ability to remove a user's verified status.
