### ISSUE TITLE
Permissions issue with creating a new document as independent sponsor

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#724]
![screen shot 2016-01-05 at 12 29 31 pm](https://cloud.githubusercontent.com/assets/764851/12123694/0c0b2904-b3a8-11e5-9eb9-d66210601ea4.png)

**Comment by cmbirk** [comment]
I requested independent sponsor, verified, and then tried to create a document.

I'm still getting an error here.  As an Independent Sponsor without any groups, my 'Sponsor as' select is empty.  If I put in a title and try to create a document I get the 'You do not have permission' error.

After inspecting the request, I'm seeing the request payload as

```
{title: "Testing Testing", group_id: null}
```

**Comment by cmbirk** [comment]
Looking like the DocumentApiController is explicitly looking for admin privileges?

```
 if (!$user->can('admin_manage_documents')) {
            return Response::json($this->growlMessage("You do not have permission", 'error'));
        }
```

**Comment by cmbirk** [comment]
Yeah, we need to check `User::getValidSponsors()` instead, but it returns a weird collection.  Looks like an individual user and groups are all mashed into one collection.

**Comment by krues8dr** [comment]
Good catch - I was so focused on the groups part that I didn't re-check independent sponsors.

**Comment by krues8dr** [comment]
That _should_ do the trick.

**Comment by krues8dr** [comment]
Fixed in dev and master and waiting on testing & deploy
