### ISSUE TITLE
Create status for documents, instead of just public/private

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#725]
Documents shouldn't be published by default as they are now, they should have to choose to publish them - either publicly or privately - before they show up on the site when you're not part of the authoring group.

**Comment by krues8dr** [comment]
Here are some statuses we'll want to support:

* Unpublished - new, not shared to anyone that isn't a document collaborator, can be previewed on the live site by logged in users who are collaborators(!)
* Private - published only to people with the link
* Published - viewable by everyone
* Deleted - not viewable by anyone (except admins)

**Comment by sethetter** [comment]
@cmbirk @krues8dr - I see there is already a `statuses` table, and some code around statuses in the `DocumentApiController` and elsewhere. Was that intended to be used for this purpose? If so I'll go ahead and utilize it.

**Comment by krues8dr** [comment]
@sethetter No, so statuses in that table are to indicate `document status` - that is, where in the legislative process the document is.  We need a different table for this.

**Comment by sethetter** [comment]
Good to know! Seems like a different word for "status" would be good for this issue. Maybe "state"?

**Comment by krues8dr** [comment]
That seems even more confusing, since `state` is usually the table you create `geographic states` in. :)  How about `document_status` for the new table ?

**Comment by krues8dr** [comment]
of `doc_status` to match our naming convention.

**Comment by sethetter** [comment]
`doc_statuses` works for me. Still seems confusing, because both `statuses` and `doc_statuses` refer to the status of a document, but two different types of statuses, lol.

Maybe `stage`? Or `publish_status`?

Naming things is hard.

**Comment by krues8dr** [comment]
`statuses_2`

**Comment by krues8dr** [comment]
Seriously though `publish_statuses` is probably pretty good.

**Comment by sethetter** [comment]
`statuses_2` it is ;)

**Comment by cmbirk** [comment]
I think `publish_statuses` or `publish_states` works

**Comment by sethetter** [comment]
I like `publish_states` best, to further differentiate from `statuses`.

![decided](https://cloud.githubusercontent.com/assets/655500/12274736/e83701ee-b931-11e5-828d-98c48c3218e0.gif)

**Comment by krues8dr** [comment]
Ok but I'm using that table to keep track of the US states we publish bills in.  :trollface:

**Comment by sethetter** [comment]
So be it :)

**Comment by sethetter** [comment]
@krues8dr @cmbirk to clarify - the `unpublished` state is intended to allow access to the document only for users who are part of the group it belongs to or who are an individual sponsor on it, right?

I saw the word "collaborators" above, but that seems to suggest anyone who has annotated / commented on it. Is the above correct?

**Comment by krues8dr** [comment]
@sethetter yeah, you've got it right there.
