### ISSUE TITLE
ability for users to delete or remove documents 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovfoundation/madison#732]
Hey folks ! Jumping off emails w/ Bill, wanted to put in a suggestion for the later queue. 

I'm user: https://mymadison.io/user/edit/25

Currently, on documents or /docs/107, I don't see an option to delete or remove the draft. Seems useful. 

Could live under document information tab?

**Comment by cmbirk** [comment]
I think this is the same as #363, which is on our immediate priority list.  For now I would say mark as private.

**Comment by cmbirk** [comment]
![mark document private](https://cloud.githubusercontent.com/assets/764851/12155327/0f2e9408-b48a-11e5-95b6-55d27f1b6c6f.png)

**Comment by davidmooreppf** [comment]
Ha, my bad, I had looked for that checkbox and didn't see it. User failure.
