### ISSUE TITLE
user can create document, but not associated group 

### ISSUE THREAD

**Issue by davidmooreppf** [opengovfoundation/madison#733]
Small issue, maybe idiosyncratic. 

I can create a doc as user: https://mymadison.io/user/edit/25, but my associated active group, Participatory Politics Foundation (which doesn't seem to show a public identifier on Madison?) can't sponsor one as of now - gets the "there was an error submitting..." error. 

Totally realize these workflows are in active development, just in case it's helpful. Delete this if you like.

**Comment by cmbirk** [comment]
That's great feedback.  Thanks @davidmooreppf .  We're taking a look

**Comment by krues8dr** [comment]
This is now fixed in dev and master and just waiting on testing & deployment.
