### ISSUE TITLE
Chrome isn't breaking cache.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#734]
It looks like chrome is now ignoring cache-busting via url parameters - I had it happen earlier, and just watched it happen for Nicko.  Looks like we'll have to find a more better solution here.

**Comment by krues8dr** [comment]
The thing to do is probably add the cache busting into the path to the file, and .htaccess rewrite to remove it.  e.g. `/css/fdjsaklfdjsaklfdsj/style.css` => `/css/style.css`.

**Comment by cmbirk** [comment]
Does nginx use the same .htaccess file?

**Comment by krues8dr** [comment]
nginx does not use .htaccess. :/

**Comment by krues8dr** [comment]
We also probably should force some cache date invalidation on the templates too via headers.

**Comment by cmbirk** [comment]
Yeah, that's what I thought.  Is there a comparable file for nginx, or does everything reside in the vhost?

**Comment by krues8dr** [comment]
In the vhost.  Nginx compiles its config.

**Comment by krues8dr** [comment]
We could symlink in the build process?

**Comment by krues8dr** [comment]
Nevermind, then we're back where we started with asset management in github.

**Comment by cmbirk** [comment]
Yep, ok.  Just going to have to do a good job making it clear in documentation what the setup is for each.

**Comment by krues8dr** [comment]
Fixed in 3.0
