### ISSUE TITLE
User Account Creation & Log-In Process

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#74]
I like Change.org's sign in/log-in process: takes you to a new page w/ "Log In with Facebook" or other accounts on one side or "Sign Up" on the other.  But I like RapGenius' better (with everything inline, thereby "ranking" the method we want folks to sign up...we'd put log in with email address first).

Once you sign up, I like RapGenius' flow straight to the profile page.

**Comment by cmbirk** [comment]
I think we pretty much have this figured out, but if you'd post some screenshots here, we can integrate them into the new designs.
