### ISSUE TITLE
If mailer info isn't setup properly, signup succeeds but returns an error.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#742]
We should probably try/catch this somehow.  The user's account will end up being created, but they will never received their confirmation message and won't be able to login as a result.

**Comment by dkd903** [comment]
I ran into this same issue when I was trying to signup for Madison for the first time on my local dev setup.

**Comment by dkd903** [comment]
I am trying to work on this issue. This is how I am approaching it, correct me please if I am wrong:

1. Start the try catch block after a new user is created and get the user's ID
2. The mail routine in the Try block
3. The user delete routine is in the catch block.

Also, what would be the correct way to delete the user - delete() or destroy()?

**Comment by krues8dr** [comment]
I don't think we want to delete the user here - instead, I'd just confirm the user automatically if no confirmation message can be sent.  I think that this is the path with the least friction for the end user.  Does that sound ok?

**Comment by dkd903** [comment]
Sounds good. Thanks!

**Comment by dkd903** [comment]
@krues8dr I am running into the following issues:

1. APP_ENV is set to local and APP_DEBUG=true in my .env, still index.html is being served instead of pre-build.html
2. After I login, I still see the Login and Signup menu bar at the top - is there some caching setting?

I was wondering if I am missing something?

**Comment by krues8dr** [comment]
Something is broken here - we've had several users signup, but *no* emails are being sent.

**Comment by krues8dr** [comment]
I'm seeing `Class 'App\\Http\\Controllers\\Mail' not found`

**Comment by sethetter** [comment]
Should be resolved now!
