### ISSUE TITLE
Instructions to install in ubuntu all plataform

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#761]

**Comment by dkd903** [comment]
I pulled down the source both on my mac and ubuntu 14.04 LTS. I guess I could probably write-up the  instructions for Ubuntu. Just have a question - when you say All Platform, would it suffice if I write it only for the 14.04 LTS?

**Comment by krues8dr** [comment]
Yes, Ubuntu 14 would be great for now!

**Comment by krues8dr** [comment]
Fixed with PR #879
