### ISSUE TITLE
Check email address validation.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#765]
I just saw that a user was able to create an account with an invalid email address - we should check that this is being checked properly.

**Comment by cmbirk** [comment]
It appears this is [not a simple](http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address) issue, so it depends on how in depth we want to go on this check.  I'm not very worried about this in our current state, as we send out validation emails.  This will, however be an issue when we get to being able to comment / annotate without verifying email. ( We have an issue for that which I will reference here )

**Comment by cmbirk** [comment]
#635

**Comment by krues8dr** [comment]
Obviously a regex isn't the best way to do this, but to start I'd be happy with changing the form input to the new html5 "email" type for now.  That'll at least keep users from doing something silly.

**Comment by cmbirk** [comment]
:+1:
