### ISSUE TITLE
Can't create a document

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#767]
https://github.com/DCgov/dc-madison/issues/24#issuecomment-170693546

@cmgiven can you list the steps that led you to the error?

**Comment by cmgiven** [comment]
* Clicked My Documents
* Under the Create a Document header, entered title and sponsor.
* Upon clicking the submit button, was taken to a broken page with the error message.

**Comment by krues8dr** [comment]
Great, thanks - and who were you trying to create a document as (the sponsor)?

**Comment by cmgiven** [comment]
Executive Branch.

**Comment by sethetter** [comment]
@cmgiven was the group verified? Locally I'm not able to recreate given the steps you outline.

**Comment by krues8dr** [comment]
I was able to recreate on live, I'm getting the same `uibModal` error.

**Comment by sethetter** [comment]
It looks like the assets needed to be rebuilt with an updated version of the `bower_components` folder. I've done that now in the DC repo and document creation seems to work.

Can you verify @cmgiven or @krues8dr?

**Comment by krues8dr** [comment]
Works for me.  @cmgiven  ?

**Comment by cmgiven** [comment]
It works. Is there a way to delete a document?

**Comment by krues8dr** [comment]
Right now, there's no way for users to delete a document - that's in this sprint though ( #363 ).  In the meantime, you can make documents `private` under the document information tab, which will remove it from view.

**Comment by cmgiven** [comment]
Looking good. Thanks for everything today!
