### ISSUE TITLE
Flagging comment results in 500

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#771]
Looks like the url string isn't being put together properly, posts to `https://drafts.dc.gov/api/docs/34/comments/undefined/flags`

**Comment by krues8dr** [comment]
Ah, so also, under the hood we don't have any way to handle annotation-comments - only annotations and comments.  This was an oversight on my part I think.

**Comment by krues8dr** [comment]
And we have no table to store the `meta` of this.  Ugh.

**Comment by cmbirk** [comment]
We're discussing rolling `annotation_comments` into the `comments` table for simplification, which would mean we could do the same with the meta table.  Ideally we would have a parent `Comment` class that `AnnotationComment` could extend, and this _is_ in favor of a single table.  I quickly scanned for a couple resources on how this might work with Eloquent:

https://laracasts.com/discuss/channels/eloquent/multiple-models-to-same-table
http://stackoverflow.com/questions/20292329/how-to-implement-a-self-referencing-parent-id-model-in-eloquent-orm

**Comment by krues8dr** [comment]
After lengthy discussions on the topic, it sounds like we're in favor of merging `annotations`, `comments`, and `annotation comments` (aka replies) into one table.  If we want to align this with the original ideas from the [W3 Web Annotation Working Group Data Model](https://www.w3.org/TR/annotation-model/), we'll need to make several modifications.  

We can assume that the database record will not be a perfect 1:1 match with the annotation model, and some translation will need to be done on the API end to produce well-formatted annotation model compliant data.  This frees us to add additional data that will make it more easily queryable for us, such as a madison-specific type : `annotation` or `comment` are the obvious choices, with replies to either type being a `comment` that has a `parent_id`.  

Per the likely outcomes in #122, we'll also need a way of keeping track of previous revisions of a comment or annotation; we also need to make this easily queryable.  The performance on `select unique(id)... group by original_id order by date desc` is not great last time I checked.  Something more robust is ideal here, like a `current` flag or the like, though that comes at the expense of being write-heavy with all the updates to remove `current`.
