### ISSUE TITLE
Text inputs cut off in Firefox

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#772]

**Comment by krues8dr** [comment]
This is great for now - we do in the future need to use `rem` here though to preserve the rhythm.  Not a big deal at the moment.

**Comment by cmbirk** [comment]
It's actually just zero-ing out a padding that bootstrap had set.  The 12px is a bootstrap padding that only affects the horizontal spacing between the text and the side of the input.

**Comment by krues8dr** [comment]
:+1: Awesome, thanks!
