### ISSUE TITLE
Mobile interface issues

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#776]
- [ ] Homepage alignment off (some parts flush left)
- [ ] Annotation bar char statistics and oppose/support button alignment off
- [ ] Annotator name overlaps with annotator comments
- [x] Menu links can only be opened in new tab (by holding them)
- [x] Menu bar auto-opens when loading a legislation page via the homepage
- [ ] Annotation statistics at top of legislation page overlap with header logo
- [x] Annotation sidebar goes off screen when opened
- [ ] Legislation metadata gets squashed and elongated on mobile #808 
- [ ] Gap between featured document and feature image on small screens #809

**Comment by krues8dr** [comment]
Thanks for these!

For context: the annotation piece in particular is problematic for us.  Mainly, the experience of _annotating_ on mobile is universally bad and a really hard problem to solve.  People generally don't do much annotation on phones - with the possible exception of highlighting in iBooks/Kindle/etc (so that might be a good place to start).  

Second, our mobile experience has taken a back seat in our development priorities, since we have so very few real users actually _interacting_ with the site on phones. There is another ticket here ( #599 ) just mentioning that so we have a link between the two.

**Comment by emanuelfeld** [comment]
For sure. Perhaps the mobile site can remove annotations (for the time being) and just show the policy text, with a note to view the site on a desktop browser to annotate and giving links to send the page via email, social, or what not. 

I agree that few people are going to want to annotate on their phones. Only concern on my end is that there is likely going to be a push of this stuff through social media channels (twitter, washingtondc reddit, etc.) and people might arrive through mobile (at least the first time).

**Comment by emanuelfeld** [comment]
Might also see how Medium and genius.com do annotations. Genius' is pretty similar to the sidebar glossary on http://open.dc.gov/open-source-guidelines/.

**Comment by mattbailey0** [comment]
I'd second the approach of graceful degradation for annotations on small screens, especially if true feature parity is a ways off.

**Comment by krues8dr** [comment]
@emanuelfeld @mattbailey0 Just FYI: we're meeting this morning about the mobile experience and prioritizing that for today/tomorrow.  We'll loop you all in in this ticket as we come up with answers.

**Comment by krues8dr** [comment]
@emanuelfeld @mattbailey0 We made a first push on this today, and things are looking considerably better than they did 8 hours ago.  We just deployed that, please have a look and get back to us.  We still have a few issues we know about and there are issues open for those.

**Comment by emanuelfeld** [comment]
Thanks a ton, @krues8dr, @sethetter, and @cmbirk! Looking so much better.

**Comment by mattbailey0** [comment]
<3

**Comment by sethetter** [comment]
V4 had a UI overhaul, and I think these are all addressed. Closing this! If there are new mobile problems open a new issue for it.
