### ISSUE TITLE
Annotation sidebar must be closed to click on other comments 

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#777]
Bubbles on the right might also not be necessary. Should just be able to click the highlighted text to open the annotation. Change color of annotation based on number of comments.

<img width="773" alt="screen shot 2016-01-12 at 12 40 20 pm" src="https://cloud.githubusercontent.com/assets/4269640/12271565/c40309ce-b929-11e5-8461-a4a52b1d212e.png">

**Comment by krues8dr** [comment]
We've talked about the color change for number of comments (basically heatmapping) but you get into a plethora of issues for usability down that rabbithole.

**Comment by emanuelfeld** [comment]
Was thinking more changing the lightness of the highlight, rather than the color.

**Comment by krues8dr** [comment]
Same problem - it's already hard to get an acceptable range for contrast standards, I think we're under it already.

**Comment by sethetter** [comment]
New UI in v4
