### ISSUE TITLE
Clicking the currently-opened annotation anchor should close the sidebar.

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#780]
Just a UX tweak.  If I pull out the sidebar and keep my mouse on the same annotation anchor and then re-click the anchor, it should close the sidebar.  The use case here is if I'm just browsing through the anchors without engaging in the sidebar.

**Comment by emanuelfeld** [comment]
I think the sidebar should close whenever you click outside of the sidebar. On my browser, opening the sidebar covers the annotation anchor (completely, unless I have the window full screen).

**Comment by krues8dr** [comment]
If the sidebar were a modal, I'd agree - but since it's not, and it sits next to the content, I'm inclined to call closing it without explicit closing by the user an unexpected behavior.

**Comment by sethetter** [comment]
New UI in v4
