### ISSUE TITLE
Hide OAuth logins if config not set

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#782]
Currently, if the twitter / fb app keys aren't set the buttons break.  We need to hide the buttons if the corresponding configs aren't set.  This wouldn't be hard to do with the `/api/settings/vendors` route.

This is also in reference to https://github.com/DCgov/dc-madison/issues/50

**Comment by dkd903** [comment]
Started working on this issue. But I get an error:

> FatalErrorException in UserController.php line 539: Class 'App\Http\Controllers\OAuth' not found

![screen shot 2016-02-21 at 3 29 17 pm](https://cloud.githubusercontent.com/assets/233879/13205187/edce5420-d8af-11e5-9560-81c2445dccb0.png)

Is the OAuth library missing from the codebase?

**Comment by sethetter** [comment]
During the upgrade to Laravel 5, OAuth login was broken. There's a new package to handle this, called Socialite, provided by Laravel. For now though, the existing OAuth code will be removed and we'll open another ticker for implementing OAuth logins with the new package.

https://phabricator.opengovfoundation.org/T73
https://phabricator.opengovfoundation.org/T76

**Comment by sethetter** [comment]
No oauth in v4!
