### ISSUE TITLE
Menu fixes

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#787]
Per #776.

* [ ] Menu links can only be opened in new tab (by holding them)
* [ ] Menu bar auto-opens when loading a legislation page via the homepage

**Comment by sethetter** [comment]
I'm not able recreate either of these on my desktop with mobile emulation or on my actual phone (Nexus 6). Am I missing a step here?

**Comment by krues8dr** [comment]
@emanuelfeld reported it, pinging him.

**Comment by emanuelfeld** [comment]
Ok, looks like the problem on my end (iPhone 6) is that the hamburger menu does not close after you've clicked a menu item. If the menu is open when you click on a legislation from the homepage, it will remain open when you arrive at the legislation's page.

**Comment by sethetter** [comment]
@emanuelfeld got it, thanks for the clarification!

**Comment by krues8dr** [comment]
Since it's a SPA, that's to be expected I think.  We'd have to watch for location changes and then trigger the bootstrap close menu event.

**Comment by sethetter** [comment]
@krues8dr I figured it at least makes sense to collapse the menu after a link from within it is clicked (touched). Maybe not for links outside the menu though (menu should be manually closed in that case).

Thoughts?

**Comment by krues8dr** [comment]
:+1:

**Comment by emanuelfeld** [comment]
@sethetter should I be seeing this live yet?

**Comment by krues8dr** [comment]
@emanuelfeld Not yet. If everything goes well, we'll probably do one more deploy today before CoB that'll include this.

**Comment by emanuelfeld** [comment]
Got it.
