### ISSUE TITLE
Home Page "Latest Activity/News" Feed on the Right Side of the Page

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#79]
Instead of the "Getting Started" box there now, a catchy news feed like RapGenius' one.  I'm talking about the big boxes on the right side of the page (screen shot attached), with the dates/times/sharing and the pretty content and info.  

This would pull in latest activity on Madison across the site, as well as pull in general news related to issues/bills/docs in Madison.  Like Google/Bing news + Madison activity.

![screen shot 2014-01-22 at 12 18 37 pm](https://f.cloud.github.com/assets/2349231/1976368/6943cc80-8389-11e3-921a-77e3335a01bf.png)

**Comment by cmbirk** [comment]
Closing this in favor of our overall redesign.
