### ISSUE TITLE
Allow visitors to view and scroll through all annotations for a document

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#790]
Perhaps two levels to this feature request:
1. A user can open up the annotations side panel and scroll through them (not having to individually click on annotations to open them up).
2. A user can scroll through the annotations panel and the document will automatically jump to the relevant section of the document.

**Comment by krues8dr** [comment]
The site used to work that way and we actually got rid of it. The problem then was that there was simply too much content to scroll through easily, and there was no connection between annotations and your place in the document, it was a mess with all the jumping around.

**Comment by emanuelfeld** [comment]
Maybe I should wait to see how the annotations feed works. For documents where there are ongoing edits, I'd appreciate a way to be able to see what people have recently commented on (and what they said).

**Comment by emanuelfeld** [comment]
Did your original implementation have the second item in the list?

**Comment by krues8dr** [comment]
Yup.

**Comment by krues8dr** [comment]
For your use case, a "new" indicator would be more useful, I think.

**Comment by cmbirk** [comment]
Yeah, something to the effect of an unread badge.

We do need to think through models of consumption here though.  For example, there's a person that I would like to track on the current DC open data document and view all of his discussion on the document because I appreciate his expertise.  We don't have an easy way to do that at the moment.

**Comment by emanuelfeld** [comment]
I don't think you would want an unread badge next to the edit/annotation itself. For lines with a lot of annotations, you would have to scroll to the bottom to see it. Instead, perhaps an option at the top to only show edits/annotations made in the past X amount of time or since you last visited.

**Comment by sethetter** [comment]
Single comment feed at bottom of page in v4!
