### ISSUE TITLE
Hovering problematic when multiple superimposed edits/annotations

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#796]
Here, for instance, when hovering, only the whole passage annotation/edit appears in the tooltip, not the one for the "law." change.

![image](https://cloud.githubusercontent.com/assets/4269640/12307031/e39424a8-ba0a-11e5-833e-86a93dbedfb7.png)

**Comment by krues8dr** [comment]
This is another one of those really hard problems that no one has solved well.  Whenever you've got overlapping annotations this can potentially occur.  It's also really hard to determine if one annotation completely contains another.  To solve this, we've provided the sidebar links.

**Comment by emanuelfeld** [comment]
Can you assign each passage an id, which any edits/annotations for part or all of the passage inherit. Then you can display all of the annotations for a given passage on hover of that passage.

**Comment by emanuelfeld** [comment]
I guess that's kind of duplicating the sidebar..

**Comment by emanuelfeld** [comment]
My pov is that we could get rid of the hover display all together. Make the passages clickable, so that they open up the sidebar for that passage.

**Comment by sethetter** [comment]
New UI in v4, should be better now!
