### ISSUE TITLE
Time stamps for annotations are off by several hours

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#804]
We're losing the timezone information when it comes from the API I think - we should make sure we're sending that in all cases.

**Comment by emanuelfeld** [comment]
Unsure if the same, but it's not possible that the original comment was one day ago and the response was two days ago.

![image](https://cloud.githubusercontent.com/assets/4269640/12358377/e60ca9f0-bb7a-11e5-86c6-b541f7f1fe5c.png)

**Comment by JoshData** [comment]
I just posted something to the Discussion tab and it's listed immediately as "5 hours ago", so something is jumping into UTC.

**Comment by dkd903** [comment]
Looks like there was a difference between the formats of the created_at dates for the annotation and for the comments.

    "created_at":"2016-02-21 07:05:56", //annotation (not RFC format)
    "created_at":"Sun, 21 Feb 2016 07:06:37 +0000", //comment on annotation

Have pushed a fix now.
