### ISSUE TITLE
Consider ways to make Discussion tab more prominent

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#806]
So far, it looks like users are missing (or ignoring) the Discussion tab in favor of annotation.  That's great for our overall use case, but I'm worried that people might not know this is even an option.  We should consider ways to make the Discussion option more prominent or obvious.

I was talking to @mattbailey0 and @joshdata about this one on Slack earlier, so looping them in here.

**Comment by JoshData** [comment]
+1 This matches my experience on the site.

**Comment by sethetter** [comment]
New UI in v4
