### ISSUE TITLE
Legislation metadata gets squashed and elongated on mobile

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#808]
Using iPhone6, safari browser.

Could probably go under the document title.

![img_0343](https://cloud.githubusercontent.com/assets/4269640/12329385/2ca068c0-baae-11e5-844e-eaa2eeac1c55.PNG)

**Comment by krues8dr** [comment]
After staring at this for a while now, I'm thinking that changing the two-columns into one-column-stacked on mobile is a good plan.
