### ISSUE TITLE
Alignment inconsistencies across pages

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#810]
Using Chrome 47.0.2526.106 on el capitan.

drafts.dc.gov, header, and other text aligned
![image](https://cloud.githubusercontent.com/assets/4269640/12331276/e528df50-bab6-11e5-863f-fe0a0713ce01.png)
no padding for header or text, left of drafts.dc.gov
![image](https://cloud.githubusercontent.com/assets/4269640/12331308/fe3ee106-bab6-11e5-8e00-04e9e2521965.png)
header not padded, left of text and drafts.dc.gov
![image](https://cloud.githubusercontent.com/assets/4269640/12331317/05862456-bab7-11e5-98e8-4e9a2e65a50f.png)
header not padded, left of text and drafts.dc.gov
![image](https://cloud.githubusercontent.com/assets/4269640/12331323/0d129efc-bab7-11e5-8f4c-f628e3a47f87.png)

**Comment by sethetter** [comment]
New UI in v4
