### ISSUE TITLE
Allow admins to export comments as a CSV

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#813]
I couldn't find the other issue documenting this, so this is probably a dupe.  Just want to capture this functionality.

Super-useful filters:
- all documents for a user or  a single document
- date range

Should be threaded to include replies in the proper order.

**Comment by krues8dr** [comment]
Right now, site owners can do this manually with the following mysql query:

```
SELECT 'comment' AS type, id, '' as quote, text, created_at FROM comments WHERE doc_id = 30 UNION SELECT 'annotation' as type, id, quote, text, created_at from annotations where doc_id = 30 UNION SELECT 'comment-annotation' as type, annotation_comments.id, '' as quote, annotation_comments.text, annotation_comments.created_at from annotation_comments LEFT JOIN annotations ON annotation_comments.annotation_id = annotations.id WHERE annotations.doc_id = 30 INTO OUTFILE '/tmp/dc_comments.csv' FIELDS TERMINATED BY '\t' ENCLOSED BY '"' LINES TERMINATED BY '\n';
```

**Comment by akuckartz** [comment]
Why CSV ?

**Comment by krues8dr** [comment]
@akuckartz That's what was requested.  If you'd like an alternative format, please let us know!

**Comment by akuckartz** [comment]
@krues8dr RDF ! That could be rendered using CSV and https://www.w3.org/TR/2015/REC-csv2rdf-20151217/ or using JSON-LD or Turtle.

**Comment by krues8dr** [comment]
@akuckartz Considering none of the offices we work with have any practical application for RDF or LD in general, we probably won't be implementing that any time soon.  Unfortunately, linked data remains a highly technical, purely academic pursuit right now and in the absence of any commonly-used consumer tools - or even anything to link _to_ - it doesn't really make sense for us to spend time on it right now.  A CSV file can be opened and used by every office we work with, on the other hand - just drop it into LibreOffice or MS Excel and off you go.

That being said, we _are_ actually invited experts on the [W3C Web Annotation Working Group](https://www.w3.org/annotation/), because of our interest in legal annotation.  That group is currently working on a linked data model for annotation.  Since we do not yet have a finalized recommendation, and the current Draft is changing on a weekly basis, it would be premature for us to implement it at this time - and of course, that would be the standard we'd be using if we were to do this.

**Comment by sethetter** [comment]
Done in v4
