### ISSUE TITLE
Comment tally should include comments on annotations

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#820]
The comment tally that appears at the top of the right column currently only includes Discussion comments. It should also include comments that folks put on Annotations, since those are otherwise not captured and seem to be where a lot of the engagement happens once you hit saturation on annotations. Alternatively, comments on annotations could be counted as annotations also, since the difference is somewhat academic. But the current UI seems to favor the first option. 

per @mattbailey0 cc: @cmgiven

**Comment by cmbirk** [comment]
This was resolved in the above merge.
