### ISSUE TITLE
Allow multiple featured documents.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#825]
Per request from DC, there should be a way to have more than one featured document.

**Comment by krues8dr** [comment]
This is stored in the `settings` table, which only has 255 characters allowed in the `meta_value` field.  That's enough for a *huuuuge* number of document ids, comma-separated.  But that might not be the most elegant way to handle this.   @cmbirk thoughts here?

**Comment by krues8dr** [comment]
It looks like the Featured Document site setting feature is broken right now, too.  
![screen shot 2016-01-19 at 1 35 47 pm](https://cloud.githubusercontent.com/assets/127904/12428248/92f67586-beb1-11e5-9b8f-c6854d3e430d.jpg)

**Comment by cmbirk** [comment]
I think that the newly build document stages might be a good way to solve this

**Comment by krues8dr** [comment]
I'm not sure they are, thought about that.  Whether a document is featured is a parallel, but different, piece of metadata.  That is, if a document becomes featured, it doesn't have a "special status", behaviorally it's still a public document from the system's perspective.  Shoehorning a meta property in there seems the wrong solution to me.

**Comment by cmbirk** [comment]
Hmm.  You're not modifying the query much, and I can imagine having a few Document model property arrays that specify what states count as public, private, or inaccessible.  That's just a mapping to an `in` sql clause.  You can just group by the state to pass the needed arrays to the homepage, and the regular document pages aren't changed.

**Comment by krues8dr** [comment]
I'm not sure what the viewability of a document has to do with it's status as a "promoted" document, aside from the obvious requirement that an inaccessible document cannot be viewed.  `a :: b != b :: a` here.

**Comment by cmbirk** [comment]
It doesn't necessarily with the "promoted" document specifically, but it's rather looking at stages a bit more abstractly than the specific use case we're using them for now.  Just trying to keep from duplicating this data if there's no need.

**Comment by krues8dr** [comment]
That's fair.  I'm seeing it as just another metadata `tag` on the document itself, though - there's no reason why we couldn't let each sponsor feature their own documents at the top of their sponsor's page, for instance.  The site-wide tag is just picked by the admins.

**Comment by cmbirk** [comment]
Yeah, that makes sense, but also works with the `states` model without creating the new tab.  For each sponsor page you're still going to query only their documents, you'd just group by state and show featured first.

This doesn't solve the issue of only the admins being allowed to set featured documents though, so you'd just get into Featured Wars with the sponsors.  Hmm

**Comment by cmbirk** [comment]
So there may have to be a combination of both.  The sponsor sets the `featured` state on their documents, and the admin picks which sponsor-set featured documents are featured on the homepage - which would be another tag on the document itself

**Comment by krues8dr** [comment]
Ok, all this is good, but way more than I have time to resolve today and we're still waiting on the other status changes.  I'm going to do the quick and easy solution for now and just throw more ids into that field.

**Comment by krues8dr** [comment]
This still needs work, `featured` should be a property on the doc itself, eventually.
