### ISSUE TITLE
Add Ability to See All Past and Pending Document Sponsor Verifications

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#834]
RIght now, can only see pending ones.  Administrators should be able to see pending requests for groups and independent sponsors, as well as the ones that have been approved or denied in the past (without having to go to databases, etc).  

<img width="895" alt="screen shot 2016-01-21 at 12 43 01 pm" src="https://cloud.githubusercontent.com/assets/2349231/12489182/05f25c30-c03d-11e5-8597-5ba43ce2addd.png">

**Comment by krues8dr** [comment]
This is a big ask.  That's basically an entire administrative record of all changes around users in the database.  Nontrivial to do this. We don't keep track of that information currently.

**Comment by seamuskraft** [comment]
Gotcha.  Concerns are there: how would a DC government administrator be
able to see who (and by whom) users were given particular privileges?  What
if a rogue user requested to be an independent sponsor of documents as,
say, a Councilmember or other top city official?

Up to ya'll on when and how this gets tackled.  Just want gov-side folks to
at least be aware of this unfortunate and hopefully rare possibility in the
interim.

- Seamus

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation <http://OpenGovFoundation.org>
Ph: +1-760-659-0631
Tweet Us @FoundOpenGov <http://twitter.com/foundopengov>

**Comment by krues8dr** [comment]
Yup, problem-space is well defined, the solution is just very complicated and heavy.  Audit log for the entire system will take a while to implement, it's basically an entire new layer on top of what's there.

**Comment by sethetter** [comment]
Fixed in v4
