### ISSUE TITLE
Hide Like/Flag buttons until Likes are fixed.

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#836]
I can't `like` anything on drafts.dc.gov:

![image](https://cloud.githubusercontent.com/assets/4592/12532175/288ca6f2-c1db-11e5-8725-8286db9243a5.png)

![image](https://cloud.githubusercontent.com/assets/4592/12532180/3b1969cc-c1db-11e5-9b42-091ed3e5f53f.png)

It's happened on multiple separate comments on different threads.

**Comment by krues8dr** [comment]
Yup, dupe of #683 :(

**Comment by konklone** [comment]
Ah, sorry -- I did search for open issues with "likes" before opening. #683 is closed, so it didn't come up. Should #683 be re-opened til the fix is deployed?

**Comment by krues8dr** [comment]
Sorry, also dupe of #778 though not obviously. :( :(

**Comment by konklone** [comment]
Since #771 looks like a pretty big refactor, it might be good to make a quick interim patch that hides the like and flag buttons until it's deployed, since right now they are just broken.

**Comment by krues8dr** [comment]
Fair point.

**Comment by sethetter** [comment]
Likes/flags working in v4
