### ISSUE TITLE
Group creation form obscures state name

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#838]
I'm using Chrome 48. The state dropdown box on the group creation form doesn't show the state name, it gets cut off:

![image](https://cloud.githubusercontent.com/assets/4592/12532190/7fae2532-c1db-11e5-84e9-a4d8dfe7161c.png)

**Comment by krues8dr** [comment]
Seems like this was part of #772 that got missed.

**Comment by sethetter** [comment]
Fixed in v4
