### ISSUE TITLE
Group system is unclear to new users

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#839]
I created an account on drafts.dc.gov, and in the dropdown menu under my logged-in name, I can create groups and have them be subject to approval. Creating a group requires entering a street address and phone number. It's difficult to make decisions about this part of the application, because there's no explanation anywhere of what groups are or how they would function.

This also applies to the "Use Site As" function in the dropdown -- it's not clear what that means, even once I have an (unapproved) group created that I can use the site "as". I can make some guesses, but some explanation somewhere would be a huge help.

**Comment by sethetter** [comment]
This has been overhauled in v4
