### ISSUE TITLE
Document creation available, even without ability to sponsor

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#841]
I don't have the ability to sponsor documents (I see the setting to apply to be an independent sponsor, which I haven't yet used), but I can still start the Document Creation process:

![image](https://cloud.githubusercontent.com/assets/4592/12532208/ec396e14-c1db-11e5-8f59-8bea4afd54b6.png)

The "sponsor as" dropdown has no options. This is pretty confusing -- if I can't sponsor documents yet, better not to make this option available to me at all.

**Comment by krues8dr** [comment]
:+1: We're currently rewriting the permission system per #726 so this is halfway-done right now. :(

**Comment by sethetter** [comment]
Fixed in v4
