### ISSUE TITLE
Responsive breakpoints need some adjustment

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#843]
On drafts.dc.gov, in Chrome at a certain size (my default size), the design gets shoved to the edges of the viewport and overflow horizontally:

![image](https://cloud.githubusercontent.com/assets/4592/12532220/3ec8d804-c1dc-11e5-95f1-7c7a115938c5.png)

It looks like my `<body>` size is 1194px:

![image](https://cloud.githubusercontent.com/assets/4592/12532222/50705a46-c1dc-11e5-8ddc-3b5f01f2e92b.png)

**Comment by sethetter** [comment]
UI overhaul in v4.
