### ISSUE TITLE
GitHub link to this repo on drafts.dc.gov

### ISSUE THREAD

**Issue by konklone** [opengovfoundation/madison#844]
I got to this repo and filed issues because of the top link on https://drafts.dc.gov/about to this repository:

![image](https://cloud.githubusercontent.com/assets/4592/12532226/8204b390-c1dc-11e5-9858-c5e18aac1215.png)

However, the second link in that block, and the link on the homepage, are to https://github.com/DCgov/dc-madison.

So it looks like the intended one is https://github.com/DCgov/dc-madison and I was just unlucky and clicked on the one that linked to this repo instead of the DCgov fork one. Should the issues I filed here be reopened there?

**Comment by krues8dr** [comment]
Nope, all core Madison issues are correctly reported here. That repo is for the DC instance of Madison, but 99% of bugs need to be fixed upstream here and then will be pulled back to that repo.

**Comment by krues8dr** [comment]
That is, it's fine if people report issues over there, we migrate anything that's affecting core back here to be fixed, and link back to the issue there.

**Comment by konklone** [comment]
Gotcha. Still, you probably want to make it so all the links on drafts.dc.gov point to the same repo, right?

**Comment by krues8dr** [comment]
I don't think so.  For the latest version of Madison, they should be coming to this (upstream) repo, but to report bugs about DC's Madison they should be directed to the downstream repo for visibility to the DC team.

**Comment by konklone** [comment]
I understand why that seems logical, but unless you're linking specifically to a roadmap file on the upstream repo, it's pretty confusing to link to two different repos in that screenshotted block.

**Comment by krues8dr** [comment]
Sure, we can link to the roadmap file.

**Comment by sethetter** [comment]
Closing this since there's an issue on the DC repo.
