### ISSUE TITLE
After sign in from documents page, get redirected to homepage

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#850]
Haven't tried from other pages, but probably applies to those as well.

**Comment by krues8dr** [comment]
Ok, so this doesn't seem to happen if you use any of the four points of interaction on this page (Oppose/Support, Add a Comment, Add an Annotation, Add an Annotation reply) - those all use the modal popup.  From what I can tell, this only is a problem if you click the login link at the top of the page, which does take you to a different page.

**Comment by doshitan** [comment]
This is resolved in v4.
