### ISSUE TITLE
Angular templates are being cached by the browser.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#861]
I've seen this happen a few times already.  We need a way to cache-bust the templates, not just the other assets we deliver.

**Comment by dkd903** [comment]
Have tried [this solution](https://gist.github.com/ProLoser/6181026) earlier on one of my projects. Seems to work fine. There is [another here](https://gist.github.com/ecowden/4637806) as well.

**Comment by krues8dr** [comment]
Fixed in 3.0
