### ISSUE TITLE
Foreign key constraint on comments is backwards.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#873]
I should be able to delete a user and their comments should cascade-delete, however right now I get an error, 

> ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`wichita_madison`.`comments`, CONSTRAINT `comments_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`))

This looks like the relationship is inverted.

**Comment by krues8dr** [comment]
@doshitan I think you'll end up fixing this with #771

**Comment by sethetter** [comment]
Fixed with #771
