### ISSUE TITLE
Allow comments to be turned off.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#874]
We need a toggle that closes the document for commenting and annotations - comments and annotations should still be visible to read, but not reply to.  This means hiding the reply buttons, comment buttons, and disabling annotator on those pages.

On the document editing side, this should just be a toggle "Comments On / Comments Off".  In the future we'll probably want to add "Comments Hidden" as well (again, like Wordpress does) - so maybe this shouldn't be a flag as much as a value from a list, on the database side.

**Comment by mattbailey0** [comment]
LMK if this should be a separate issue, but it would also be really great to see some integration with the front page for this.  A few notions, not all of which are compatible:
- If comments on, the document should always appear before documents with closed comments
- If comments on/off there should be a visual indication of that status (think green/gray button) on the stubs on the homepage to prompt users.
- If comments are closed, the document does not appear in the "Active Legislation" or perhaps "Most Active Documents" section.

**Comment by krues8dr** [comment]
I'm :+1: on all of these.

**Comment by sethetter** [comment]
@mattbailey0 all sounds good to me! I'll roll it in with this issue.

**Comment by cmbirk** [comment]
Ideally you'd set up annotator as read-only instead of removing it to maintain the annotation hovers

**Comment by krues8dr** [comment]
I think there was a call to remove annotation hovers since they duplicate the sidebar and are confusing?

**Comment by sethetter** [comment]
It would be different based on whether it was set to "hide discussion" or just "close discussion" as well. But I'm open to removing annotation hover. Personally I prefer the sidebar.

**Comment by cmbirk** [comment]
That can be pretty confusing.  Using the screenshot from the Draft Open Data Bill on drafts.dc.gov as a very basic example.  Which period is each sidebar element referring to?

<img width="1430" alt="screen shot 2016-02-18 at 10 37 51 pm" src="https://cloud.githubusercontent.com/assets/764851/13165955/79e772c4-d690-11e5-9fa8-f234a3393d57.png">

**Comment by krues8dr** [comment]
Well, we're talking about a couple of different problems there.  I think we talked a while ago about having on hover or on select of an annotation, the color would change to indicate the relationship between the two.  That would be relatively easy.

A separate problem is that users really should not be highlighting just punctuation or single characters.  We should probably have some messaging around that if the character count is < 5 or something.

**Comment by krues8dr** [comment]
Either way, I don't think having two different ways of viewing the annotation improves the experience, I think it's pretty confusing as-is.

**Comment by sethetter** [comment]
+1 on the 5 character limit. Either way, the issue of removing annotation
hover is outside of the scope of this issue, so I'll handle it accordingly
for now.


Seth Etter
