### ISSUE TITLE
Remove assets from github.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#875]
Rebuilding the assets after every merge is getting to be a hassle.  Since we're using deployment tools internally, this would be better to do the asset building on deploy.  Since anyone using our tools will need to `composer install` etc anyway, this isn't a huge extra step.  Moving everything towards NPM ( opengovfoundation/madison-editor#38 ) will make this smoother as well.

**Comment by krues8dr** [comment]
Complete in 3.0

**Comment by sethetter** [comment]
This makes me happy :)
