### ISSUE TITLE
Move to using single PUT route for updating all doc attributes

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/madison#876]
We have a ton of routes that are single purpose for updating different attributes on a document, which is less than ideal. Instead, we should use a single `PUT` route that accepts new attributes, applies them to the specified document, validates them and then returns error messages from anything that fails, or a success message.

We'd need to make sure we have good model validation as well. Looks like [this method](http://daylerees.com/trick-validation-within-models/) would be good to adopt.

**Comment by sethetter** [comment]
It would be great to eventually move to using [resource based routing](https://laravel.com/docs/5.1/controllers#restful-resource-controllers) on the laravel side. It would clean things up significantly.

**Comment by cmbirk** [comment]
And even a PATCH route would be ideal.  Not sure how easily that's implemented in Laravel.

**Comment by sethetter** [comment]
PATCH definitely. That would follow the standard more accurately.

**Comment by krues8dr** [comment]
Well, in the long run we want a PUT here because we should be sending the whole object, not the piecemeal method we're doing now.  Have a look at how I'm handling this on the Editor.
