### ISSUE TITLE
Hide overflow on featured images

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#889]
There's some ugliness happening on featured images that are too tall.  We need to crop these eventually, but instead for now we should just hide the overflow.

![screen shot 2016-03-04 at 11 30 13 am](https://cloud.githubusercontent.com/assets/127904/13533034/92a2037a-e1fc-11e5-825a-29a44bceafdf.jpg)

**Comment by krues8dr** [comment]
This still needs the ability to remove images that have been uploaded, particularly when a new featured image is uploaded.  We also need a more intelligent way of doing that then making up filenames based on our preset sizes - we really need to have a table to keep track of attachments, and their many versions (or in this case, sizes).

**Comment by sethetter** [comment]
Featured images no longer supported in v4
