### ISSUE TITLE
IE9 - Fix styles

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#896]
I'm 99% sure this is hitting the [IE 9 Selector Limit](https://blogs.msdn.microsoft.com/ieinternals/2011/05/14/stylesheet-limits-in-internet-explorer/) which is why only half the styles are rendering.  

I tried `css-split` yesterday but ran into issues with `usemin`'s asset replacement in `pre-build.html`, so today I'm going to try out `blesscss` instead.

**Comment by krues8dr** [comment]
@sethetter I think this is now working, can you verify, please?

**Comment by sethetter** [comment]
@krues8dr looks mostly good, I don't see the image on the homepage loading though. Looking into why now.

**Comment by krues8dr** [comment]
Yeah, saw that too.  I assume I've used background properties not supported by IE9.  :/

**Comment by sethetter** [comment]
Bummer.. :( Are you digging in on that, or should I?

**Comment by krues8dr** [comment]
I'll get to it in a bit. :)

**Comment by sethetter** [comment]
:+1:

**Comment by krues8dr** [comment]
@sethetter :point_up: Can you have a look at this last commit and let me know if that looks ok and works for you?  I tried to comment the funny bits.  There's lots of url/path mangling happening and it's less than ideal.

**Comment by krues8dr** [comment]
Re: #903

**Comment by sethetter** [comment]
@krues8dr seems to be working! Nicely done :+1:

**Comment by krues8dr** [comment]
I missed a template change here.  Reopening.
