### ISSUE TITLE
IE9 - Check & Fix Annotation

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#898]
We spent a *lot* of effort making Annotator work in IE9 previously - we still have [our own fork](https://github.com/opengovfoundation/annotator/tree/ie-testing) to that end.  I'm no longer sure if this works in our current version of Madison, and it looks like the community version of [Annotator](https://github.com/openannotation/annotator/) is effectively dead (though the [Hypothes.is version is still around](https://github.com/hypothesis/h/tree/920e0138cc673c27fa19692b8efea48c04013a50/h/static/scripts/annotator)).

**Comment by sethetter** [comment]
Did we have report of this *not* working in IE9 somewhere? It all seems to be functional on my end.

**Comment by krues8dr** [comment]
Nope, just on my list of "things that are likely to break"

**Comment by sethetter** [comment]
Cool, looks all good here then.
