### ISSUE TITLE
Document Page: Add General News Feed to Each Document/Public-Facing User Page or Issue Page

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#90]
The news feed would pull in latest activity for that bill, as well as latest news (via Google news, Bing News) and latest "major" waypoint activity (like if the bill moves from draft to formally introduced), and individual social shares/discussion activity, etc.  

Each type of item in the news feed should be colored/labeled as to where it came from, when, and when the user clicks on it they're taken to the source of that news item.

**Comment by cmbirk** [comment]
Closing this in favor of the new designs.
