### ISSUE TITLE
IE9 - $injector:modulerr

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#900]
Looks like the root cause of #893 as reported is that assets built for production throw a `$injector:modulerr` error.  Doesn't happen with dev assets.  So some step in our build process is breaking things - likely suspects are `uglify` or possibly the order scripts are being added is wrong.

**Comment by sethetter** [comment]
@krues8dr I can't seem to recreate this in my VM. Is there a step I'm missing?

I forced the `index.html` file to load instead of `pre-build.html`. Source shows it's loading the built asset files. No issues so far.

**Comment by krues8dr** [comment]
I think this was fixed with the build process tweaks, seems ok now.
