### ISSUE TITLE
IE9 - Page title has hash appended to it

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/madison#901]
It's kinda weird!

Throwing this in with #893.

**Comment by sethetter** [comment]
I'm having a really hard time tracking down how to prevent this. I think it's relatively low impact though, so I'm going to punt on it for now and focus on more important issues.

**Comment by krues8dr** [comment]
This is still open afaik, we'll just lower the priority.

**Comment by sethetter** [comment]
Fixed in v4
