### ISSUE TITLE
Improve Display Compatibility with Internet Explorer 11

### ISSUE THREAD

**Issue by benblankley** [opengovfoundation/madison#912]
The layout in Internet Explorer 11 is different than expected. Basic site functionality works: user registration, commenting, annotating.

Also, the "Only secure content is displayed." message appears when the site is first loaded.

![ie11_01](https://cloud.githubusercontent.com/assets/4343490/13883786/150113fe-ecf9-11e5-9629-0ad72f4ad83f.png)
![ie11_02](https://cloud.githubusercontent.com/assets/4343490/13883785/14fc2542-ecf9-11e5-8d27-3e8ba1a5dc14.png)
![ie11_03](https://cloud.githubusercontent.com/assets/4343490/13883784/14fb5b1c-ecf9-11e5-9379-6d9c7838be9f.png)

**Comment by krues8dr** [comment]
Thanks for the report.  It looks like a lot of this is fonts, and the annotations on the side, both of which are addressed in #893.  The latest dev build looks pretty good, we will be rolling that out next week.  Here's how that looks right now:

![screen shot 2016-03-18 at 12 18 02 pm](https://cloud.githubusercontent.com/assets/127904/13884274/aacc9af2-ed03-11e5-9a36-971f4329a3c7.jpg)

There are still a few remaining issues with spacing/padding/overlap that we'll address going forward, but the major issues should be resolved soon!

**Comment by krues8dr** [comment]
@benblankley this _should_ be resolved now, please let us know if it's not.
