### ISSUE TITLE
Notifications on replies

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#917]
It doesn't look like we're currently sending notifications when someone replies to a comment/annotation.  We should add this, and include the text of the new comment/annotation (properly html-stripped to prevent attacks) and whether the reply is coming from a sponsor.

**Comment by krues8dr** [comment]
We need something here also to allow users to turn off notifications for all replies (under the user's settings page).  

A nice-to-have feature would be a way to turn off notifications for just a single document as well, from that document's page - however we don't have any way to manage settings for individual users preferences on the document page itself.  If we don't have a solid idea here of how to do that, I'm ok with punting on that part for now.

**Comment by doshitan** [comment]
Fixed in #947.
