### ISSUE TITLE
Growl messages in Angular showing in the wrong place

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#918]
Something in the CSS or templates broke and now messages appear at the top of the screen.  My first guess would be that the load order of the CSS is causing the default styles to override our custom ones.

**Comment by doshitan** [comment]
Where are the messages suppose to appear? They currently (as of 8ca4ead) appear in the top right for me which is the default for the library we are using and I don't see anywhere we change that.

**Comment by krues8dr** [comment]
This may have actually already been fixed at some point and I didn't realize it!  If they are hovering over the content at the top right, and not appearing at the top of the page and pushing the content down, then this is working perfectly!

**Comment by doshitan** [comment]
That's how it's working for me, so I'll close the issue. If someone can reproduce the problem, feel free to reopen.
