### ISSUE TITLE
Replace Grunt

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#919]
Our asset pipeline could use some work, flat Node scripts would be far better here.

**Comment by cmbirk** [comment]
What's the benefit of flat node scripts over Grunt / Gulp?  I would recommend moving to gulp.  The streams are much nicer.

**Comment by krues8dr** [comment]
Because Gulp is just one more extra tool that we don't really need.  You can do pretty much everything with just NPM that you can do with Gulp.  

http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

My vote was for `make`, but that requires everyone to actually learn how to use `make`. ;)

**Comment by cmbirk** [comment]
I actually really like what that guy set up in that article.  Didn't think I would.  Touché
