### ISSUE TITLE
Interface for "discussion as" group or individual

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/madison#922]
There is a "Use Madison As.." menu option right now that isn't fully functional. A better interface for this might be to include the option to post a piece of discussion as a particular group or the individual user account directly in the areas where comments / discussion happens.

Would love to hear more discussion about the best way for this to work.

**Comment by krues8dr** [comment]
Yeah, I think the better UX here is every time you go to comment have a dropdown that lets you choose who you are commenting as if you're a document sponsor.  However, groups cannot comment currently, so we'll have to deal with that in the database (and reintroduces our previous problem of polymorphic associations, which we did all of the #888 work to avoid).

In the meantime, I think we should have members of the document sponsor's group to be flagged as such.

**Comment by krues8dr** [comment]
There are a few interesting use cases to keep in mind here:

### Users may want to post as different identities:
* Users that want to post as themselves, without their org. e.g. "John Smith"
* Users that want to post as themselves, as a part of their org.  e.g. "John Smith (Anytown Clerk's Office)"
* Users that want to post as the org themselves.  e.g. "Anytown Clerk's Office"

This probably means that there is a data differentiation between "owner" of a comment and how that user is displayed publicly.  This probably also impacts whether individual comments are able to be associated back to a user's personal account, or the group's account.

### Information about users will change over time.

Users may cease being a part of a sponsor's group, but we don't want to lose the relationship that the users once held, for comment history purposes.  E.g., if a user made a comment as a member of a city's team and then left that job, the original comment should keep the group association for display purposes.  This means we must be careful what we choose to join based on, and will likely need redundant information in the record.

However, information about the users *themselves* may change, and we *must* update the data on the record to match this - if a user changes their name for any reason, the original associated name should *always* be changed in the historical record.  E.g., I change my name from John Smith to Jane Smith, all of the original comments I've made should reflect this and keep their association with my main account.

**Comment by sethetter** [comment]
Related - #1024

**Comment by sethetter** [comment]
Not a feature we're supporting in v4. Closing unless that changes!
