### ISSUE TITLE
 `vagrant up` should just work

### ISSUE THREAD

**Issue by doshitan** [opengovfoundation/madison#938]
If we ship a Vagrant file, folks generally expect to be able to get going with just a `vagrant up`, that's the point. Our Vagrant setup has been broken since at least the upgrade to Laravel 5.
#445 and #934 are related and there's some work going on to use Chef as a provisioner which would help here.

I think the best way forward here is to:
- [ ] Rip out any existing Vagrant stuff (since it's outdated and broken)
- [ ] Reintroduce Vagrant with #445 or when we get a custom provisioner setup that we are going to maintain

The end result being that new contributors can get to work with just `vagrant up` and we have at least one common environment to develop and test against.

**Comment by krues8dr** [comment]
:+1:

**Comment by doshitan** [comment]
This is resolved in v4.
