### ISSUE TITLE
Improve theming (part 2)

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#944]
The current theming method is to create a handful of "override" files for css, locale, etc which replace the content of the main theme.  A better way would be to do as most CMS do - have a folder of theme files nicely packaged (locale, templates, css, etc) altogether, and allow admins to pick a theme in the administrative dashboard of the application somewhere.  

Assuming this would just allow users to re-theme our existing Angular application, and not being an entirely new front-end, this requires:
- [ ] A way of packaging all of the theme files together
- [ ] A way of setting the locations of the files needed by Angular 
- [ ] Documentation on creating a new theme using ours as a base
- [ ] Potentially a way of indicating which version of the app the theme has been tested against/supports.  Minor version changes could potentially break existing themes, since template files will need to change as we update.

An example of this done well is Wordpress.  They also have done a great job with localization - with a base localization supporting many languages that can be uses globally in all themes, but can be overridden by an individual theme.

**Comment by krues8dr** [comment]
@barryvdh @abihas  any thoughts or feedback you have on this would be appreciated!

**Comment by sethetter** [comment]
Moving away from customizable instances in v4.
