### ISSUE TITLE
Email customization

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#945]
We need a better way to let people customize outgoing emails from the system.  Right now, it requires users to replace the email template files, but we can use the new content management piece of our application to store these templates in the database instead.  We'll need a way to let users insert replacement tags into the templates for template-specific data ( login link, the recipient's name, etc) - these will be different on each template though.

**Comment by krues8dr** [comment]
One additional thought here: in the future, it would be nice to allow users to indicate their language preference on the site on signup, and send emails in their particular language whenever possible.  We'd have to store multiple versions of each email in multiple languages for that.  We wouldn't want to do that now.  (We should open a new issue for this when we complete this one.)

**Comment by sethetter** [comment]
Moving away from customizable instances in v4.
