### ISSUE TITLE
HTML with Plain Text emails

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#946]
We should have a way to allow a plain text email body to be sent along with the html one.

The easiest way to do this is just replace html links with parenthesized urls, and then strip tags.  E.g.,

`<a href="http://google.com/">Let Me Google That For You</a>` 

would become

`Let Me Google That For You ( http://google.com/ )`

A harder way to do this would be to allow users to edit both bodies separately, but this seems like a lot of extra work for the end user.

**Comment by doshitan** [comment]
This is resolved in v4.
