### ISSUE TITLE
Re-review permissions

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#949]
It looks like right now Group Editors can add/remove members of groups.  Not sure if that's as intended or not.

**Comment by emanuelfeld** [comment]
Definitely seems like a bug. I'm unclear on what the staff role amounts to. Would be nice if permissions could be set on a per document basis, i.e. so editors (or staff) of groups cannot delete the documents others created within that group.

**Comment by sethetter** [comment]
Permissions overhauled in v4. Should be good now!
