### ISSUE TITLE
Command line installation for ubuntu 32 bits?

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#950]

**Comment by krues8dr** [comment]
@johnfelipe Can you tell us what didn't work from the installation instructions?

https://github.com/opengovfoundation/madison/tree/master/docs#user-content-manually

**Comment by johnfelipe** [comment]
where can i find lampp instruction for ubuntu 32 bits enviroment?

**Comment by krues8dr** [comment]
The link I posted above has Ubuntu instructions that should work for anything modern.  Let us know if it doesn't work for some reason.

**Comment by johnfelipe** [comment]
i have nginx installed to

**Comment by krues8dr** [comment]
It should still be very similar.  Again, please let us know what doesn't work from the instructions provided.

**Comment by johnfelipe** [comment]
we want to install Laravel into the /var/www/laravel directory, that is ok?

**Comment by krues8dr** [comment]
Laravel should be bundled with the app, you don't need to install it separately.

**Comment by johnfelipe** [comment]
then i need edit this
`root /var/www/laravel/public;`
for this
`/home/felipe/madison/public`??

**Comment by krues8dr** [comment]
I can't tell you how to set this up without knowing all of the details of where you put things - but in short, the `public` folder of the Madison app is where the web root should be pointed.

**Comment by johnfelipe** [comment]
For manually process in 
2. Create database and user
That is perfect command for this?

**Comment by krues8dr** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql

**Comment by johnfelipe** [comment]
https://docs.google.com/document/d/12KE_6GIi02YCdkdc4V__05wH4jzx7lAF8WmsYxKyNF4/edit?usp=sharing

I cant run your project
Pls help

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/madison$ php artisan migrate


	  [PDOException]
	  SQLSTATE[28000] [1045] Access denied for user 'madison2016'@'localhost' (us
	  ing password: YES)

In /home/felipe/madison/.env

i have 

	# Database
	DB_DRIVE=mysql
	DB_HOST=localhost
	DB_DATABASE=madison2016
	DB_USERNAME=madison2016
	DB_PASSWORD=correctpassword

How fix that?

**Comment by johnfelipe** [comment]
solved.

**Comment by johnfelipe** [comment]
I have this

http://jhonfelipeurregomejia.com:2016/

![snag-0013](https://cloud.githubusercontent.com/assets/428820/14996044/9566d4ee-113d-11e6-85ea-dd96dc7dd8d1.png)

I have in `/etc/nginx/sites-enabled/madison`

	server {
		listen 2016 default_server;
		listen [::]:2016 default_server ipv6only=on;

		root /home/felipe/madison/public;
		index index.php index.html index.htm;

		server_name 127.0.0.1 jhonfelipeurregomejia.com;

		location / {
			try_files $uri $uri/ /index.php?$query_string;
		}

		location ~ \.php$ {
			try_files $uri /index.php =404;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_pass unix:/var/run/php5-fpm.sock;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include fastcgi_params;
		}
	}

**Comment by krues8dr** [comment]
Looks like you're running in Development mode, which is causing the template to try and load the development assets, which you haven't installed.  Try setting debug=false in your .env file to trigger the production template, which will use the included pre-built assets.

**Comment by johnfelipe** [comment]
after put that config how restart?

**Comment by krues8dr** [comment]
It's PHP - no restart needed! :)

**Comment by johnfelipe** [comment]
![snag-0014](https://cloud.githubusercontent.com/assets/428820/14996455/bb0c0690-113f-11e6-841a-3c0a9bcefd21.png)

Dont work

**Comment by krues8dr** [comment]
Sorry, `APP_DEBUG=false` is the exact bit you need to change.

**Comment by johnfelipe** [comment]
works, now how implement spanish lang?

**Comment by krues8dr** [comment]
https://github.com/opengovfoundation/madison/tree/master/docs#user-content-localization

If you get it working, please send a Pull Request with the locale file back to us!

**Comment by johnfelipe** [comment]
Done about PR

Pls give me exact command for translate to spanish when translate PR to

**Comment by krues8dr** [comment]
Sorry, I meant send a PR if you create a new locale file - we don't actually want the .env file in the repo since people might accidentally commit it.  

There isn't a command to translate automatically to spanish.  You'll have to create a new locale file, based on the existing one for english, and replace each phrase with the spanish equivalent.

**Comment by johnfelipe** [comment]
`cp en_US.json es_CO.json`

when finish translate
where config my lang?

**Comment by krues8dr** [comment]
Angular translate should automatically detect your language settings from your browser.  If it doesn't, please open a new issue for that.

The default is set in the [translate module](https://github.com/opengovfoundation/madison/blob/master/public/js/modules/translate.js#L19), but in theory you shouldn't need to set that.  If you do, you'll have to install all of the asset build tools, including the rubygems, npm, and bower packages to build the app.

**Comment by johnfelipe** [comment]
/home/felipe/madison/public/js/modules/translate.js

$translateProvider.use('en_US');
For
$translateProvider.use('es_CO');

ctrl + f5 in my page but nothing change:

http://jhonfelipeurregomejia.com:2016/

**Comment by johnfelipe** [comment]
PR y 100% complete about translatio for spanish lang, but i havent that translation in my public page, pls help me
Tnks

**Comment by johnfelipe** [comment]
Anyone?

**Comment by krues8dr** [comment]
Do you need further help with this?

**Comment by IuliiSe** [comment]
hi @johnfelipe ! How did you solve the [issue](https://github.com/opengovfoundation/madison/issues/950#issuecomment-216643068) with the database password?
