### ISSUE TITLE
Its possible add a feature in home page?

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#959]
http://legislando.nossascidades.org/

That is a great app, but madison is more robust, pls tell me if possible add something like "bill projects" in home page

Stay alert

**Comment by krues8dr** [comment]
I'm not sure what you're asking here?  You can feature documents which will show up on the top left side of the homepage, by using the `Set As Featured` button on documents under `Settings`:

![screen shot 2016-05-12 at 2 42 04 pm](https://cloud.githubusercontent.com/assets/127904/15226292/27eba5f6-1850-11e6-89f0-0ca3284578b5.jpg)

You can set featured content on the top right of the homepage by editing the `home.intro.title` and `home.intro.text` in the locale files.
