### ISSUE TITLE
Notifications are not soft-deletable?

### ISSUE THREAD

**Issue by barryvdh** [opengovfoundation/madison#960]
I get this error on the notification page:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notifications.deleted_at' in 'where clause' (SQL: select `event` from `notifications` where `notifications`.`deleted_at` is null and `user_id` = 1 and `event` in (madison.user.new_group_doc, madison.user.new_activity_vote, madison.user.new_activity_comment))

It seems Notifications have the SoftDelete trait, but no `deleted_at` column. I'm not sure what is preferred, add the column or remove the trait?

**Comment by doshitan** [comment]
Yea, the Notification model had the SoftDelete trait added by accident during the Laravel 5 update. This is fixed in the dev branch with #947 by removing the SoftDelete trait usage.
