### ISSUE TITLE
how is process for git pull?

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#962]
Befor i will do it, this is commands for git pull your app?

	cd madison
	composer install
	php artisan migrate
	php artisan db:seed

**Comment by krues8dr** [comment]
I'm not sure what you're asking?  That's the process for basic installation, yes.

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/madison$ git pull
	Warning: Permanently added the RSA host key for IP address '192.30.252.123' to the list of known hosts.
	remote: Counting objects: 887, done.
	remote: Compressing objects: 100% (154/154), done.
	remote: Total 887 (delta 199), reused 167 (delta 167), pack-reused 561
	Receiving objects: 100% (887/887), 962.40 KiB | 201.00 KiB/s, done.
	Resolving deltas: 100% (457/457), completed with 92 local objects.
	From github.com:opengovfoundation/madison
	   b92369a..a8ba2c9  master     -> origin/master
	 * [new branch]      250-account-verified-notification -> origin/250-account-verified-notification
	 * [new branch]      964-group-created-notification -> origin/964-group-created-notification
	   0a495e1..df22a6e  dev        -> origin/dev
	   b9eac7f..e5010f1  issue-943  -> origin/issue-943
	Updating b92369a..a8ba2c9
	error: Your local changes to the following files would be overwritten by merge:
			public/js/modules/translate.js
	Please, commit your changes or stash them before you can merge.
	error: The following untracked working tree files would be overwritten by merge:
			public/locales/es_CO.json
	Please move or remove them before you can merge.
	Aborting

How solved this for try?

**Comment by krues8dr** [comment]
You have a merge conflict you'll need to resolve, since I brought your locale file over and patched the translate module in #961 / #966.    I'd recommend the following

1) Move your `public/locales/es_CO.json` file to `public/locales/custom/es_CO.json`.  The custom folder is for overriding the base locale, and this will preserve your site-specific changes.
2) Checkout the translate module, resetting it back to the main repo: `git checkout public/js/modules/translate.js`
3) Try again to `git pull`.

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/madison$ git checkout public/js/modules/translate.js
	felipe@felipeurrego:~/madison$ git pull
	Already up-to-date.

Not working
http://jhonfelipeurregomejia.com:2016/

![notworking](https://cloud.githubusercontent.com/assets/428820/15300406/1ed31050-1b6e-11e6-9df4-35396a8b8119.png)

**Comment by johnfelipe** [comment]
this is log of git pull

	felipe@felipeurrego:~/madison$ git pull
	remote: Counting objects: 887, done.
	remote: Compressing objects: 100% (154/154), done.
	remote: Total 887 (delta 199), reused 167 (delta 167), pack-reused 561
	Receiving objects: 100% (887/887), 962.40 KiB | 178.00 KiB/s, done.
	Resolving deltas: 100% (457/457), completed with 92 local objects.
	From github.com:opengovfoundation/madison
	   b92369a..a8ba2c9  master     -> origin/master
	 * [new branch]      250-account-verified-notification -> origin/250-account-verified-notification
	 * [new branch]      964-group-created-notification -> origin/964-group-created-notification
	   0a495e1..df22a6e  dev        -> origin/dev
	   b9eac7f..e5010f1  issue-943  -> origin/issue-943
	Updating b92369a..a8ba2c9
	Fast-forward
	 CONTRIBUTING.md                                    |   3 -
	 docs/README.md                                     |   2 +
	 .../{angular.eb78e54f.js => angular.cc26056c.js}   |   2 +-
	 public/build/angular.js                            |   2 +-
	 public/build/angular.map                           |   2 +-
	 public/build/app.745237d5.js                       |   5 -
	 public/build/app.c2135f16.js                       |   5 +
	 public/build/app.js                                |   8 +-
	 public/build/app.map                               |   2 +-
	 public/index.html                                  |   4 +-
	 public/js/modules/translate.js                     |   2 +-
	 public/locales/es_CO.json                          | 454 +++++++++++++++++++++
	 public/pre-build.html                              |   2 +
	 13 files changed, 474 insertions(+), 19 deletions(-)
	 delete mode 100644 CONTRIBUTING.md
	 rename public/build/{angular.eb78e54f.js => angular.cc26056c.js} (99%)
	 delete mode 100644 public/build/app.745237d5.js
	 create mode 100644 public/build/app.c2135f16.js
	 create mode 100644 public/locales/es_CO.json

**Comment by krues8dr** [comment]
That _should_ work.  Clear your browser cache and try again?  You'll also want to verify that your browser is set to prefer `es-CO` (in Chrome, this is under Advanced > Languages).

**Comment by johnfelipe** [comment]
Is not working, i delete cookies in chrome, test in mozilla and nothing

2016-05-16 15:30 GMT-05:00 Bill Hunt <notifications@github.com>:

**Comment by krues8dr** [comment]
Can you open your Network developer tools and verify that the `Accept-Language` header is correct?

![screen shot 2016-05-16 at 4 36 46 pm](https://cloud.githubusercontent.com/assets/127904/15303198/8020f50a-1b84-11e6-83f2-acfd27d6c2ca.jpg)

**Comment by johnfelipe** [comment]
how can i do that?

**Comment by krues8dr** [comment]
In Chrome, go to the menu View > Developer > Developer Tools.  In the Developer Tools pane that opens, click Network. You'll then need to reload the page to log everything that loads.

**Comment by johnfelipe** [comment]
![develop](https://cloud.githubusercontent.com/assets/428820/15303340/dea39860-1b7c-11e6-9480-a117317433fd.png)

**Comment by krues8dr** [comment]
Great, now click the first request in the Network pane and you should get the headers for it.

**Comment by johnfelipe** [comment]
![accept](https://cloud.githubusercontent.com/assets/428820/15303417/42f3e630-1b7d-11e6-9e87-c370749d166d.png)

**Comment by krues8dr** [comment]
Ah, there you go.  Your file is for `es-CO`, but your browser is only accepting `es-ES`.  Rename `public/locales/es_CO.json` to `public/locales/es_ES.json`, clear cache, and see if that works.

**Comment by johnfelipe** [comment]
EUREKA, works

http://jhonfelipeurregomejia.com:2016/

**Comment by krues8dr** [comment]
Great.  I'll copy the file in the main repo later.
