### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#965]
Hi please tell me how translate succesfull to spanish version

**Comment by johnfelipe** [comment]
PR y 100% complete about translatio for spanish lang, but i havent that translation in my public page, pls help me
Tnks

**Comment by johnfelipe** [comment]
Anyone?

**Comment by krues8dr** [comment]
This has been merged into master and dev and should work properly.  Please let us know if it doesn't.
