### ISSUE TITLE
CREATION OF DOCUMENTS - DUMMIE

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#972]
I cant create documents with my admin user?

**Comment by krues8dr** [comment]
You still need to be a Verified User or member of a Group.  That way the proper owner will show up when the document is displayed on the front end.

**Comment by krues8dr** [comment]
Sorry, Independent Sponsor or a Group member, not verified.  Typo.

**Comment by johnfelipe** [comment]
then i need create a user, new user?

**Comment by krues8dr** [comment]
No, you can use an Admin user, but your admin must be one of those two things.

**Comment by johnfelipe** [comment]
do u have gitter, hangout or something?

**Comment by johnfelipe** [comment]
May be create a room in https://gitter.im/, for resolve question and issues.
Do u have user manual?

**Comment by krues8dr** [comment]
Here's the user manual: 

[Getting_Started_on_Madison.pdf](https://github.com/opengovfoundation/madison/files/267292/Getting_Started_on_Madison.pdf)

We prefer for any questions and issues to be reported on Github, so that we can properly triage requests & issues.  Also, as I mentioned before, we don't offer full support at this time.

**Comment by johnfelipe** [comment]
How can i accept 
I have

# The default settings for the admin user.
ADMIN_EMAIL=xxxxxx@gmail.com
ADMIN_PASSWORD=xxxxx.

But how can i login in admin UI?

**Comment by krues8dr** [comment]
At some point, that setting was replaced by the database seeder, which reads `config/madison.php`.  If you've run `artisan db:seed`, these accounts will exist.  If you have not run this command, note that *it will empty your database* and you may wish to manually create an admin account instead!

The scripts to automatically create an admin are [currently broken](https://github.com/opengovfoundation/madison/issues/957), so you'll need to do some SQL to do this. 

To manually create an admin account: 

1) signup per usual
2) in the database, make sure there is a record in the `roles` table with the name `Admin` - if not, insert a new record in this table for the role: `INSERT INTO roles SET name='Admin';` 
2.1) Get the id of the Admin record: `SELECT id FROM roles WHERE name = 'Admin';`
3) Get your admin user's ID.  If you just signed up, it's probably the last one in the database: `SELECT id, email FROM users ORDER BY id DESC limit 1`
4) Insert a new record to grant the user an admin account, replacing the ids you got from the previous steps: `INSERT INTO role_user SET user_id = YOURUSERID, role_id = ADMINROLEID`

**Comment by johnfelipe** [comment]
![done](https://cloud.githubusercontent.com/assets/428820/15349183/8b5f40c6-1c96-11e6-880e-c9ae9e6be0bc.png)

What is next step?

**Comment by krues8dr** [comment]
Ok, so now you have an Admin - Admins can approve requests to become and Independent Sponsor or member of a group.  

So, login as whichever user you want to become your document's author (as it will appear on the public site), and then decide if you want to become an Independent Sponsor (just yourself as the author) **or** create a Group (yourself and other collaborators).  

To become an Independent Sponsor, click the link on your Account Settings page:

![screen shot 2016-05-18 at 9 14 12 am](https://cloud.githubusercontent.com/assets/127904/15359811/0d07d10a-1cd9-11e6-9942-c25284c1c707.jpg)

And then fill out the form that appears with your address information.  Your status will change to pending approval.

To create a new Group, go to the Group Management page and click Create A Group:

![screen shot 2016-05-18 at 9 14 23 am](https://cloud.githubusercontent.com/assets/127904/15359843/2e5ffda0-1cd9-11e6-999b-cdf5617bc261.jpg)

And then fill out the form that appears with your address information.  The group status will change to pending approval.

After either of those steps, you'll need to login as your Admin account and Verify the Group or Independent Sponsor, depending on what you chose earlier - these options are under the Admin menu.  

![screen shot 2016-05-18 at 9 19 16 am](https://cloud.githubusercontent.com/assets/127904/15359955/9db95db8-1cd9-11e6-9d42-9f4911981482.jpg)

Just click the button for Verify next to the user or group:

![screen shot 2016-05-18 at 9 19 32 am](https://cloud.githubusercontent.com/assets/127904/15359977/b8fbc3a4-1cd9-11e6-8346-55af738cd707.jpg)

**Comment by johnfelipe** [comment]
But my account havent 
Edit documents
Verify accounts
Verify groups
...
Is an user normal no admin

**Comment by krues8dr** [comment]
If you've logged in with your admin account, those options should be present.  Try logging out and logging in with the admin user you created previously.

**Comment by johnfelipe** [comment]
this SELECT id, email FROM users ORDER BY id DESC limit 1
No show ID of last email, but i have ID of user put in .env
Why dont create admin user with php artisan db:seed?

**Comment by krues8dr** [comment]
As I mentioned before, `db:seed` no longer reads `.env`.  You'll need to follow the steps I listed above to create an admin user account.

**Comment by krues8dr** [comment]
I apologize for the confusion, we are currently in the process of restructuring things to make this much easier. ;)

**Comment by johnfelipe** [comment]
Ok that be done

2016-05-18 8:39 GMT-05:00 Bill Hunt <notifications@github.com>:

**Comment by krues8dr** [comment]
Do you need further help with this?
