### ISSUE TITLE
User notification setting descriptions need to be localized

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#974]
It looks like these are being generated from the `getDescription` in the Laravel events?  We probably want to return a code similar to what's being done in `getName()`.

**Comment by doshitan** [comment]
The `getName` method returns a "broadcast-able"/easy to use id for the event, it is not used for display purposes right now, just as an id. We could use it as the key for the translations and remove the `getDescription` method altogether.

**Comment by krues8dr** [comment]
:+1:  I am ok with this turn of events.
