### ISSUE TITLE
Clicking to verify new account from activation email does not log in the user as claimed

### ISSUE THREAD

**Issue by nickom** [opengovfoundation/madison#978]
I signed up for a new account, clicked the link to verify my account, went to Madison where the status message said "You have been verified and **you have been logged in**. Welcome [NAME]" and it didn't log me in:

![activate](https://cloud.githubusercontent.com/assets/3171982/15479248/474af4ec-20ed-11e6-821e-f6ce9952de98.gif)

**Comment by krues8dr** [comment]
Dupe #963
