### ISSUE TITLE
Consider adding a gemfile for development building

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#981]
We only need a couple of gems (compass & sass) for doing development on Madison, but having them in a Gemfile would make this easier.  This would look something like:

```
source 'http://rubygems.org'

gem 'sass', '3.4.21'
gem 'compass', '1.0.3'
```

**Comment by sethetter** [comment]
I'm going to add a `Gemfile` for capistrano in #985, so I'll tackle this there as well.
