### ISSUE TITLE
Setup Capistrano for deployments

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/madison#985]
Moving to using Capistrano to ease deployments.

**Comment by sethetter** [comment]
The goal here is to be able to deploy to our different managed instances using Capistrano. I think it would make sense to have each instance be a separate "stage". However, it might not make sense to keep the server info for each of these in our git repo. So I'm thinking we can ignore file that match a certain pattern in the `config/deploy/` folder (except for a template).

@krues8dr @doshitan thoughts?

**Comment by krues8dr** [comment]
I'm storing server-specific information in Chef Vault so there shouldn't be any need for this.  Moreover, convention > configuration in ruby. ;)
