### ISSUE TITLE
no load document

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#986]
http://jhonfelipeurregomejia.com:2016/docs/proyecto-004

Cargando, espere por favor.

How fix that?

**Comment by johnfelipe** [comment]
this is other
http://jhonfelipeurregomejia.com:2016/docs/proyecto-de-acuerdo-015
How fix that

**Comment by krues8dr** [comment]
You'll need to check the error log on the server itself, there's no way to tell what's actually happening here.  Laravel has an error log in `storage/logs/laravel.log` and the webserver should also have a separate log.  You may also need to once again turn on debugging to have the error printed.

**Comment by johnfelipe** [comment]
`/home/felipe/madison/storage/logs` is empty

`APP_DEBUG=true`

	composer install
	php artisan migrate
	php artisan db:seed

But my instance not showing
Pls help with instructions

**Comment by krues8dr** [comment]
The server is throwing a 500 error, which doesn't tell us anything other than that something isn't working.  Either the laravel log or the webserver log should have an error.

If there is nothing in the logs folder, then it's likely the webserver cannot write to the logs directory.  The entire storage folder must be writable by the user the webserver is running as - this may also be causing the error in the first place, as we store a cached html copy of the documents in the storage folder as well.

**Comment by johnfelipe** [comment]
What is correct values for this `display_errors`, `display_startup_errors`, `error_reporting`, `html_errors `and `log_errors`

**Comment by johnfelipe** [comment]
solved with

	touch /home/felipe/madison/madisonlogerror.log
	log_errors = On
	error_log = /home/felipe/madison/madisonlogerror.log
	sudo chmod -R 777 /home/felipe/madison/storage
	# Logs
	error_log /var/log/upstart/php5-fpm.log;
