### ISSUE TITLE
Loading the user's documents page sends an uncaught 400 error

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#990]
The page already says that the user doesn't have access to post documents, so the additional popup isn't needed.  We probably shouldn't retrieve documents if the user doesn't have access in the first place.

**Comment by krues8dr** [comment]
Looks like this is happening even if you do have permission to create docs.

**Comment by sethetter** [comment]
Issue is [here](https://github.com/opengovfoundation/madison/blob/2c5b6b1b7021b8226bbbc330a8a02dffe7bb40a6/server/app/Http/Controllers/DocumentController.php#L1133-L1152). The user->doc relationship needs to be cleaned out now that we have a group only model.

I'm on it.
