### ISSUE TITLE
"Sponsor As" on document page is not always defaulting to the first (and only) group.

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#991]
I've fought with this a few times - Angular's select list is _awful_ and creates a blank value if there is no value set.  I _thought_ we were setting this though, so I'm not sure why it's not working now.

**Comment by sethetter** [comment]
It's possible the select is rendering before the option is set? Wouldn't be a bad idea to move towards having data loaded in a resolve function anyways.

**Comment by krues8dr** [comment]
![screen shot 2016-06-28 at 11 22 03 am](https://cloud.githubusercontent.com/assets/127904/16421335/9e180200-3d22-11e6-87f0-d1ed4220b9b3.jpg)

**Comment by sethetter** [comment]
Sponsor system overhauled in v4. Should be good now!
